### ISSUE TITLE
Use stderr in update-gke-infra.sh

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1036]
We should update `update-gke-infra.sh` to send the initial non-log output to stderr so that we can still see the instance list and prompt but still be able to pipe or redirect the log output via stdout.

Another possible change to make it easier to redirect logs output would be to separate the `update-gke-infra.sh -c logs` command into two commands, one to list the instances and the second that takes a flag to specify the instance rather than prompting the user for that information.

**Comment by varshneydevansh** [comment]
Can I choose this task?

**Comment by aarontp** [comment]
@varshneydevansh Sorry, I just saw your message here.  I'm actually going to close this one out since this script has been deprecated recently though.  If you're still interested in contributing, there are some other easy first issues you could potentially work on.  LMK if you want help finding something.  Thanks!

**Comment by varshneydevansh** [comment]
I will look for something to work with @aarontp and let you know =)
