### ISSUE TITLE
Jobs allow list flag not working

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1038]
For some reason the `--jobs_allowlist` flag is not actually setting the allowlist in the request (as shown by dumping the request and seeing the `jobs_allowlist` parameter in the recipe part of the request being empty).  This is likely related to some of the recent recipe refactoring.

**Comment by jleaniz** [comment]
Looking into this. I think I identified the issue. The method that creates a default recipe does not include the jobs allow/deny lists passed from the command line via turbiniactl.
