### ISSUE TITLE
Ubuntu 20.04, staging tests fail

### ISSUE THREAD

**Issue by jleaniz** [google/turbinia#1040]
[Run local stack e2e test (ubuntu:20.04, staging)](https://github.com/google/turbinia/runs/6064074313?check_suite_focus=true#logs)

Looks like we might need to edit requirements.txt to allow google-cloud-core>=2.0
error: google-cloud-core 1.7.2 is installed but google-cloud-core<3.0dev,>=2.3.0 is required by {'google-cloud-storage'}

**Comment by aarontp** [comment]
Looks like we're seeing this issue in stable now as well

**Comment by aarontp** [comment]
It was changed recently in this PR: https://github.com/googleapis/python-storage/pull/741/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7
