### ISSUE TITLE
plaso VSS option incorrect

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#1080]
https://github.com/log2timeline/plaso/blob/9cc50c972b257d6cbbea38fa8b39f0bf027e0960/plaso/cli/storage_media_tool.py#L581

^ option should be --no_vss in below location
https://github.com/google/turbinia/blob/86158a95a0b134978628c1680d0997667ec7c935/turbinia/workers/plaso.py#L43

Please check how this will work if recipes pass in the --vss_stores option

**Comment by joachimmetz** [comment]
The current default for unattended mode is to disable VSS processing, so the `--no_vss` option should not be necessary. However I'll change Plaso UX to deprecate `--no_vss` and support `--vss_stores=none` going forward. Also see: https://github.com/log2timeline/plaso/issues/4150

**Comment by jleaniz** [comment]
Looked at this issue today and if i understand correctly, using "--vss_stores none" should not be a problem and we just need to remove any references to the now deprecated "--no_vss" option. Is my understanding correct @joachimmetz ?

**Comment by joachimmetz** [comment]
As of the (pending) next release plaso will support `--vss_stores=none` and will complain about `--no_vss`. In the future `--no_vss` will be removed.
