### ISSUE TITLE
Scripts for pulling data from redis

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1100]
As we move to use Redis more in Turbinia, it would be nice to have a couple small shell scripts utilities to pull data out of Redis.  Doesn't need to be anything heavy as we don't want to replace the API server and such, but just enough to maybe query by request so there is an example of how to construct the basic queries and filter for debugging.

Another thing we may want is to have a dump/restore script so updating is easy with the new architecture.  Not sure if we want to do this with these scripts or not as there is likely redis tools more suited for this, so I'm not going to file a separate issue yet, but wanted to include it here just in case we need to write some scripts or want to do it at the same time.

**Comment by jleaniz** [comment]
Fixed in #1299
