### ISSUE TITLE
TypeError - Returning string object from docker_manager but expecting binary data later. 

### ISSUE THREAD

**Issue by HolzmanoLagrene** [google/turbinia#1121]
If a docker container is specified in the config file the method `execute_container` of the `ContainerManager` returns `stdout` and `stderr` values.

https://github.com/google/turbinia/blob/0dcd2da32072a8b331e66f9370317b631aae1819/turbinia/workers/__init__.py#L655-L658

A little later in the same method, these values are written to file and a binary output is expected:

https://github.com/google/turbinia/blob/0dcd2da32072a8b331e66f9370317b631aae1819/turbinia/workers/__init__.py#L713-L714

However, the `ContainerManager` returns string values for `stdout` and `stderr`.
https://github.com/google/turbinia/blob/0dcd2da32072a8b331e66f9370317b631aae1819/turbinia/lib/docker_manager.py#L272-L275

This leads to a type error as demonstrated here:
```
turbinia-worker2   | 2022-08-23 12:25:43 [ERROR] PlasoTask Task failed with exception: [a bytes-like object is required, not 'str']
turbinia-worker2   | 2022-08-23 12:25:43 [INFO] Traceback (most recent call last):
turbinia-worker2   |   File "/usr/local/lib/python3.8/dist-packages/turbinia-20220701-py3.8.egg/turbinia/workers/__init__.py", line 1028, in run_wrapper
turbinia-worker2   |     self.result = self.run(evidence, self.result)
turbinia-worker2   |   File "/usr/local/lib/python3.8/dist-packages/turbinia-20220701-py3.8.egg/turbinia/workers/plaso.py", line 132, in run
turbinia-worker2   |     self.execute(
turbinia-worker2   |   File "/usr/local/lib/python3.8/dist-packages/turbinia-20220701-py3.8.egg/turbinia/workers/__init__.py", line 713, in execute
turbinia-worker2   |     fh.write(stdout)
turbinia-worker2   | TypeError: a bytes-like object is required, not 'str'
```

**Proposition**: The file handlers in the lines 699 and 713 should be `w+` instead of `wb`.

**Comment by aarontp** [comment]
Thanks for the report, we'll take a look at this (should be an easy fix, thanks for digging into it).

Just a heads up -- We've mostly moved to executing the entire worker in the docker container instead of just executing the individual task binaries in containers, so eventually this feature may go away.  Let us know if you still see a good use for it. 
There are now pre-built docker containers that should contain all the current dependencies for the worker.

**Comment by HolzmanoLagrene** [comment]
No problem - thanks for the quick answering!

Well, thats interesting! Because i thought this feature to very nice. To me it would make a lot of sense to keep this feature as it allows to very specifically use the docker containers as kind of _plugins_. This has various advantages:

- I can use the exact e.g. plaso distribution i want to use and alter in a way that suits my purpose e.g. use a different entrypoint or hardwire some parameters. 
- I can pack my own processor into a container including all requirements and it is guaranteed to work. 
- Finally, i think its a very nice way to decompose the systems and work on a specific subsystem without touching a) the other systems and b) the host system that allows c) to create test scripts for all the container and check whether they behave as expected.

Maybe i can explain my setup, then you can better understand my idea:
I use a local docker setup with a server and multiple workers. Each worker runs on a different physical host and gets the hosts _docker-socket_ mapped into the worker docker container. Each job, then spawns a new docker container on the phyiscal host, but controlled by the worker. Which in my opinion makes it a very clean setup, also in terms of setting up new worker machines.

Of course, using the docker setup kind of doesnt fit into the whole server-worker architecture as the worker again spawns a new but different kind of "worker"...

Also after submitting the issue i realized that my proposition would be even safer if the `subprocess` would specifically add an encoding to guarantee `strings` as return values. I would suggest something like this.

```
text: If true, decode stdin, stdout and stderr using the given encoding
    (if set) or the system default otherwise.
```

```
proc = subprocess.Popen(
    cmd, shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE,
    cwd=cwd, env=env, text=True, encoding="utf-8")
```

**Comment by aarontp** [comment]
Sounds good, yeah, some of those ideas are why we initially added the docker execution mechanisms.  I think we're fine keeping it as long as people are actually using it and hopefully it shouldn't be a lot of extra maintenance.  

Thanks for the fix details for this one, we can create a PR for it (or we're also happy to accept PRs :)).

**Comment by HolzmanoLagrene** [comment]
For some reason the Agreement Thingy seems not to be working. The rest should be fine...

**Comment by aarontp** [comment]
The CLA bot did eventually approve, but for some reason it didn't update the PR, not sure why.  It's approved/submitted now.  Thanks for the PR!
