### ISSUE TITLE
Scale GKE nodes in addition to pods

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1123]
Currently we scale on pods, but it would be nice to scale on nodes as well.

**Comment by aarontp** [comment]
FYI @wajihyassine

**Comment by wajihyassine** [comment]
Briefely tested this while I was building out the Celery/Redis k8s scripts and it seemed fine ,just need to run a few tests to confirm but changes should hopefully be minor. Will assign to add this in sometime when the Celery/Redis k8s deployment is merged.

**Comment by wajihyassine** [comment]
GKE autoscaling docs: https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler

Would just need to add in `--enable-autoscaling --min-nodes=1 --max-nodes=MAX` then adjust `.clusterconfig` accepting a minimum node and maximum node assuming no other problems
