### ISSUE TITLE
Update terraform config

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1135]
We've recently added a few new config variables but the terraform config is not yet updated with this and the dev e2e tests are failing:
```
turbinia.TurbiniaException: Required config attribute /root/.turbiniarc:CLOUD_PROVIDER not in config
```
We need to sync the config to make sure it's up to date.

**Comment by wajihyassine** [comment]
Fixed in https://github.com/forseti-security/osdfir-infrastructure/pull/68
