### ISSUE TITLE
Set task start time on worker

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1195]
Currently the start time is set when the Task is initiated, and this is done on the server when the job is created.  When the tasks are in a queued state for a long time then this mean that the run time can be misleading.  We should move this to be set once it starts on the worker.   We can create a new "create_time" (or similar) attribute that is set on the server side and then we can compare the overall run time against this to see how long things have been queued for (and add this to monitoring).

**Comment by aarontp** [comment]
Related: #1198

**Comment by wajihyassine** [comment]
Fixed via adding `worker_start_time` which is calculated form worker in: https://github.com/google/turbinia/pull/1215

Not sure if you want to include the monitoring queued times as part of this issue if so can re open else seems to make more sense for a separate issue
