### ISSUE TITLE
Configure API docs to be exposed via readthedocs.io

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1196]
https://github.com/google/turbinia/pull/1128/files adds API documentation so we should make sure that is put with the rest of the docs on readthedocs.io.

**Comment by aarontp** [comment]
FYI @jleaniz

**Comment by jleaniz** [comment]
Add content to ```turbinia/api/cli/README.md``` for the new cli tool

**Comment by jleaniz** [comment]
Closed in #1238 and #1251
