### ISSUE TITLE
Change Web UI path outside of /tmp

### ISSUE THREAD

**Issue by jleaniz** [google/turbinia#1200]
Edit the config tempalte and change the WEBUI_PATH to something other than /tmp

**Comment by wajihyassine** [comment]
So looked into this we actually do set the path to `/web/dist` and tested to confirm it works: https://github.com/google/turbinia/blob/1d1c0ed7d46232dff4cb410197033e8165858ddb/docker/api_server/Dockerfile#L13

I think while we were testing we changed it to /tmp and confirmed that dist files are not left in `/tmp/web` after it gets built in container only if we change the path in dockerfile will the dist folder be outputted differently.

The API client PR will have the `WEBUI_PATH` so just need to be sure to set it to `/web/dist` and then should be set
