### ISSUE TITLE
API Server returning completed_with_errors on a Request still running

### ISSUE THREAD

**Issue by wajihyassine** [google/turbinia#1241]
So as I was doing some load tests, I noticed that a Request status would evaluate to `completed_with_errors` if there are no Tasks currently running and task count did not equal # of failed or successful counts for a failed or successful status.

I think the only situation this should actually evaluate to `completed_with_errors` is if the Tasks never ran, which the server would timeout and mark as failed or if there are failed tasks which we're not checking in this case. 

For the case when there are no Tasks running, I believe we should have a `pending_or_unknown` status and leave the `completed_with_errors` only for if the request is complete and we identified failed Tasks

**Comment by jleaniz** [comment]
Should be fixed in #1277
