### ISSUE TITLE
ewfmount uses outdated libewf library

### ISSUE THREAD

**Issue by HolzmanoLagrene** [google/turbinia#1250]
### Problem

The worker docker image still uses `libewf` with Version `2014-08-14` as distributed by apt. This version is known to create errors.

### Solution

Build libewf from source and add the code to the dockerfile. The following code would produce working results:

```bash
sudo apt update
sudo apt install git libfuse-dev python3-dev autoconf automake autopoint libtool pkg-config flex bison byacc zlib1g-dev bzip2 libssl-dev

sudo git clone https://github.com/libyal/libewf.git
cd libewf/
sudo ./synclibs.sh
sudo ./autogen.sh


sudo ./configure --prefix=/usr --enable-python
sudo make
sudo make install
sudo ldconfig
```

**Comment by joachimmetz** [comment]
20140814 is the latest legacy pre-release from  Jul 16, 2022 (also see: https://github.com/libyal/libewf-legacy/releases/tag/20140814) Using the experimental version from https://github.com/libyal/libewf.git IS NOT RECOMMENDED.

@HolzmanoLagrene can you describe what issues you're seeing?

**Comment by joachimmetz** [comment]
Also the version is 20140814 NOT `2014-08-14`

**Comment by joachimmetz** [comment]
> This version is known to create errors.

Can you provide more details? Did you file a issue with the libewf project?

**Comment by HolzmanoLagrene** [comment]
Wow this escalated quickly :smile:. Thanks for the quick assist.

Maybe it's all my mistake. The issue originated from an error with the message `pysmraw_handle_read_buffer: unable to read data`. However, I did some tests and it turned out that my E01 was corrupted.

Nevertheless from my personal experience and based on past problems I had, I made the experience that some problems went away with the latest code and building it myself. I can not however reproduce or provide more details.

@joachimmetz no i did not file an issue that time, as my own build solved the problem. Is there a reason for this specific timestamp. It really confused me it seems.

I will close the issue myself in a couple of minutes.

**Comment by joachimmetz** [comment]
> pysmraw_handle_read_buffer: unable to read data

@HolzmanoLagrene this error message has nothing to do with reading E01 files (writing them maybe), so this issue is unrelated to ewfmount

> Wow this escalated quickly smile

Next time VALIDATE your claims BEFORE you make them, better yet have them CONFIRMED by an authoritative source
especially somewhere public (if you're working in DF you should know better)

**Comment by HolzmanoLagrene** [comment]
Yeah that was my bad. I'll keep that in mind for next time. At the time I thought this to be the solution as it has been for me in the past, but I should have tested more thoroughly. Anyway thanks and sorry for the inconvenience!
