### ISSUE TITLE
Update e2e test scripts

### ISSUE THREAD

**Issue by wajihyassine** [google/turbinia#1255]
We should update the [googleclouddisk.sh](https://github.com/google/turbinia/blob/master/turbinia/e2e/googleclouddisk.sh) script as we phase out PSQ to instead use the new CLI params to create a request and we can also pull logs from the API server itself rather than relying on stackdriver/GCS.

**Comment by jleaniz** [comment]
Review and refactor all e2e tests to use the APi server and turbinia-client instead of turbiniactl

**Comment by jleaniz** [comment]
Closed in #1463
