### ISSUE TITLE
Implement Task Prioritization

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1276]
It would be nice to have the ability to prioritize tasks so that we can get triage results back first, and potentially have multiple stages of triage processing.   This will be especially useful now that dfTimewolf uses streaming containers so we can get initial results back while other things are still processing: https://github.com/log2timeline/dftimewolf/pull/747.

**Comment by jleaniz** [comment]
Is this a duplicate of #1244 ?

**Comment by aarontp** [comment]
@jleaniz Yeah, I think so, good catch.  Closing it out.
