### ISSUE TITLE
jobs_completed_total counter not covering all job completions

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#1297]
The `jobs_completed_total` counter is not implemented to cover all possible ways a job can be set to completed and as such is incorrectly representing the total jobs completed.

https://github.com/google/turbinia/blob/67e7654e1902dbe9ec593365de943c5b70a33e78/turbinia/task_manager.py#L69

**Comment by hacktobeer** [comment]
It looks like it does cover all jobs. Some jobs error out because eg a target file to analyse can not be found. This is WAI....but I think we can improve the code to *not* throw a job error but let the job finish with a relevant message instead of just a job error.

**Comment by aarontp** [comment]
@hacktobeer Should we rename/update this issue to track the job error issue you mentioned then?  Can you point to where this happens?

**Comment by hacktobeer** [comment]
Let's close this for now, as I changed the metrics type from Gauge to Counter, which should give a better representation of the different job metrics. I will test when the new release is deployed.
