### ISSUE TITLE
Coin miner domain and wallet extraction

### ISSUE THREAD

**Issue by wajihyassine** [google/turbinia#1300]
Create a new Job that can help identify whether a coin miner is on a machine. 

A first good step could be to detect the xmrig miner, which typically is installed on the machine with a ` config.json` file so if that file is found, can then grep the config file to determine if it has any of the fields related to the xmrig config.

See here for example of what it looks like: https://github.com/xmrig/xmrig/blob/master/src/config.json

What can be useful is extracting the coin, url, user, and pass from the pools field.
```
    "pools": [
        {
            "coin": null,
            "url": "donate.v2.xmrig.com:3333",
            "user": "YOUR_WALLET_ADDRESS",
            "pass": "x",
```

FYI @aarontp in case you had any other thoughts

**Comment by hacktobeer** [comment]
How about using our yara scan job with some coin 
miner detection rules like below. 

https://github.com/Neo23x0/signature-base/blob/master/yara/pua_cryptocoin_miner.yar

**Comment by wajihyassine** [comment]
Ah good idea, looks like they cover more miners too as well as XMRig: https://github.com/Neo23x0/signature-base/blob/master/yara/pua_xmrig_monero_miner.yar

I guess we should already be running these yara scans then per Dockerfile? https://github.com/google/turbinia/blob/d9e2faae208971c33b4c338050a176e012a0938e/docker/worker/Dockerfile#L85C18-L85C63

Thinking then if there is a hit on a miner, we can at least pull the domain or wallet address rather than just getting a hash hit so possibly a Job/Task that can further process the Yara scans?

**Comment by Fryyyyy** [comment]
We've talked about this previously - maybe in a bug? - and decided there's nothing we can do with the information

**Comment by wajihyassine** [comment]
Yeah I remember we did, don't remember where, but this resurfaced again which I was thinking even tracking the wallet would help detect wallet re-use through correlation, but thinking more, I don't know what the chances are of that happening (each miner may get its own ID unless it was user configured) + data itself may still not be useful minus possible attribution.

Also quick Google search I do see some relevant articles but doesn't seem like they were able to grab much more than transaction IDs  + dates or trying to find address re-use.  ( e.g.  [here](https://www.fraudinvestigation.net/cryptocurrency/tracing#:~:text=What%20are%20Cryptocurrency%20Forensics%20and,identify%20perpetrators%20and%20locate%20assets.) and [here](https://www.giac.org/paper/gcfa/11168/forensic-bitcoin-cryptocurrency/147334) )

Going to close this out for now as not worth pursuing, but can chat more offline if something new resurfaces/more research was done that would be worth looking into.
