### ISSUE TITLE
Create templates to help standardize issue submissions

### ISSUE THREAD

**Issue by wajihyassine** [google/turbinia#1307]
Using [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) create templates for filing a bug or a feature request and add the appropriate labels to them (e.g. add enhancement for FR, and bug label for bugs). 

Some other label categories can be:
  * Server/Worker
  * API/Celery
  * Web

**Comment by aarontp** [comment]
We might want to set the default label to be `enhancement` as well.
