### ISSUE TITLE
Web UI: Sort / Filter Tasks

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1341]
### What would this feature improve or what problem would it solve?

Be able to find specific tasks or specific types of tasks faster.  This can be difficult when there are hundreds of Tasks for a single request.

### What is the feature you are proposing?

Be able to sort and filter the tasks in a request list.  For example being able to sort by name, status, summary, or filter based on status, or filter the summary based on a search string.

**Comment by aarontp** [comment]
Also sort by priority

**Comment by wajihyassine** [comment]
Marking as fixed per https://github.com/google/turbinia/pull/1518

With the PR you can now filter task by status (e.g. running, failed, success queued) and/or by job name and is automatically sorted by task_name. 

With how task list is currently implemented as a virtual table we won't be able to custom sort further so unless this is a huge need I believe the filters + sort on task_name should be good enough and can always open another issue down the line if it isn't. Searching for a specific task id is being tracked here: https://github.com/google/turbinia/issues/1279
