### ISSUE TITLE
Filter Container/Docker enumeration output

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1343]
### What would this feature improve or what problem would it solve?

Having fewer tasks makes it easier to see the results.  This would also give more flexibility in processing things selectively.

### What is the feature you are proposing?

Filter the Container/Docker Enumeration output to exclude snaphots by default and add a `TASK_CONFIG` variable to be able to control what get filtered out.  Make sure that the *Enumeration report output makes it clear what is being filtered out.  Also set a limit to the number of containers enumerated by default (and have corresponding `TASK_CONFIG` var).

**Comment by wajihyassine** [comment]
It'd be nice if it somehow can tag or filter k8s system level pods as I think that is one of the main causes of so many timelines/tasks and can pick out "user deployed ones"

**Comment by hacktobeer** [comment]
As per side conversation:
- filter out default system ones
- have an option to include *all* containers if user wants that
- have an option where the user can specifically provide the container names they want to have analysed (and ignore all others)

**Comment by aarontp** [comment]
I'm consolidating the other filtering of system containers into this issue as well.

Some other filtering ideas from an old thread:
- Filter last N started containers
- Show only containers with an exposed port
