### ISSUE TITLE
[Bug]: Jenkins Analysis Task unable to extract password

### ISSUE THREAD

**Issue by wajihyassine** [google/turbinia#1344]
### What steps will reproduce the bug?

1. K8s Cluster running Jenkins Helm chart: https://github.com/jenkinsci/helm-charts
2. Running dftw recipe dftimewolf gcp_turbinia_disk_copy_ts
3. Disk containing Jenkins pod gets processed through Turbinia pipeline.
4. JenkinsAnalysisTask does not pick up on the Jenkins configuration.

### What is the expected behavior?

JenkinsAnalysisTask identifies a weak Jenkins password

### What do you see instead?

JenkinsAnalysisTask returns:

```
No Jenkins instance found
Jenkins version: Unknown
```

### Additional information

Checking inside the Jenkins pod
```
jenkins@jenkins-0:/$ find . -name config.xml
./var/jenkins_home/users/jenkins_10477391727943582798/config.xml
./var/jenkins_home/config.xml
```

Grepping for field in first file
```
jenkins@jenkins-0:/$ cat ./var/jenkins_home/config.xml  | grep password
No results...
```

Grepping for field in second file
```
jenkins@jenkins-0:/$ cat ./var/jenkins_home/users/jenkins_10477391727943582798/config.xml | grep password
              <password>{PW_STRING}</password>
      <passwordHash>#jbcrypt:$2a$10$/EH.PW_STRING</passwordHash>

jenkins@jenkins-0:/$ cat ./var/jenkins_home/users/jenkins_10477391727943582798/config.xml | grep fullName
  <fullName>Jenkins Admin</fullName>
```

I would have expected the JenkinsAnalysisTask return a weak password for the second field.

**Comment by hacktobeer** [comment]
Verifying the regex used to get the artifact:
- it matches the filepath of the config.xml
-- ./var/jenkins_home/users/jenkins_10477391727943582798/config.xml
- regex: https://github.com/google/turbinia/blob/master/turbinia/workers/analysis/jenkins.py#L75

Currently k8s (GKE in this case) writes any secret that is needed in a file to a small disk (8GB). Please verify that you copied all disks to make sure you get the config.xml
It is present in the node, but it is stored in a different disk that is mounted on the node (at least on GKE).

**Comment by wajihyassine** [comment]
Updating per forgetting to add `--all_disks` flag to dftimewolf recipe.

Now it detects the Jenkins version but is unable to extract the password even though it was set as `jenkins:jenkins`

```
status": "Jenkins version 10 found with 1 credentials, but no issues detected",
```
