### ISSUE TITLE
[FR]: turbinia-client command for worker logs print 

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1363]
### What would this feature improve or what problem would it solve?

This would make it easier to debug tasks.

### What is the feature you are proposing?

Add a turbinia-client command to print out the worker logs without having to download the full task output.  This could print out `stderr-*`, `stdout-*` and `worker-log.txt` from the Task directory.  This could potentially be added to an existing command like `turbinia-client status task` instead of creating a new command.

A bonus would be to have this information exposed in the web UI as well.

### What alternatives have you considered?

You can get the same data by downloading the full task output with `turbinia-client results task`, but this way wouldn't require downloading everything (ie. plaso tasks with gigs of data) and would print to stdout which would make it easier.

**Comment by jleaniz** [comment]
Closed in #1528
