### ISSUE TITLE
Test coverage no longer showing by default

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1405]
### What is the feature you are proposing?

Test coverage numbers used to be in the default test output, but aren't showing up anymore for some reason.  It would be nice to add this back so that we can see what coverage is like easily.

### What would this feature improve or what problem would it solve?

Visibility into test coverage.

**Comment by hacktobeer** [comment]
This was disabled when moving away from nose here https://github.com/google/turbinia/commit/24746e5c75595850038879730f0e4c0101b3b159#diff-5d20bf301d1d889d7ec73948673520e35c59a2f06b78ea646f0d7f0348ff6669

Let's see if there is quick fix.
