### ISSUE TITLE
[FR]: Log API requests

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1424]
### What is the feature you are proposing?

It would be nice if the API request logging went to the same directory as the other logs.  Turbiniactl does log to that directory when the service starts up, but subsequent logs don't end up there.  As far as I can tell the API server only logs requests to stdout so they have a more limited lifetime than logging directly to the log directory.  

### What would this feature improve or what problem would it solve?

This helps with debugging issues related to the API server.

**Comment by aarontp** [comment]
Assigning to @jleaniz for triage.

**Comment by jleaniz** [comment]
Closed in #1460
