### ISSUE TITLE
[Bug]: turbinia-client prints extraneous help output

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1470]
### What steps will reproduce the bug?

Use `turbinia-client submit googleclouddisk --project <foo> --zone <bar> --disk_name <baz>` to submit processing request.

### What is the expected behavior?

Only the info about the correctly submitted processing request should be printed.

### What do you see instead?

The help output is displayed in the output even though the processing request gets submitted normally and all the required flags have been passed in.

**Comment by aarontp** [comment]
FYI @jleaniz

**Comment by jleaniz** [comment]
Fixed in #1489
