### ISSUE TITLE
[Bug]: turbiniactl in turbinia-server docker results in invalid choice

### ISSUE THREAD

**Issue by kyt999** [google/turbinia#1488]
### What steps will reproduce the bug?

Follow the documentation outlined in develop local - https://turbinia.readthedocs.io/en/latest/developer/develop-local.html 

### What do you see instead?

Step 6 results in an error:

`docker exec -ti turbinia-server turbiniactl compresseddirectory -l /evidence/history.tgz
usage: turbiniactl [-h] [-q] [-d] [-c CONFIG_FILE] [-o OUTPUT_DIR] [-L LOG_FILE] [-V] [-j JOBS_ALLOWLIST] [-J JOBS_DENYLIST] <command> ...
turbiniactl: error: argument <command>: invalid choice: 'compresseddirectory' (choose from 'config', 'celeryworker', 'server', 'api_server')` 

`docker exec -ti turbinia-server turbiniactl
2024-05-31 14:33:44 [INFO] turbinia | Turbinia version: 20240412.1
2024-05-31 14:33:44 [INFO] turbinia | Done.`

**Comment by jleaniz** [comment]
Hey apologies for the outdated documentation.  you should run 
```turbinia-client submit compresseddirectory --source_path <dir>``` instead. This is the new client which you can install via ```pip install turbinia-client``` 

https://turbinia.readthedocs.io/en/latest/user/turbinia-client.html#turbinia-api-cli-tool-turbinia-client

**Comment by kyt999** [comment]
No worries. Thanks @jleaniz 

The latest turbinia-client results in #1386 

`pip install turbinia-client==1.0.5
ERROR: Could not find a version that satisfies the requirement turbinia-client==1.0.5 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for turbinia-client==1.0.5
`

**Comment by jleaniz** [comment]
Check your pip installation, the package is released in pypi: https://pypi.org/project/turbinia-client

**Comment by kyt999** [comment]
Found the issue. TY. Newer version of turbinia-client requires-python:>=3.9,<4.0
