### ISSUE TITLE
Make sure all strings are unicode

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#15]
... Including log lines, etc.

**Comment by aarontp** [comment]
Or maybe just add:

from __future__ import unicode_literals

**Comment by aarontp** [comment]
(definitely the latter, as following suit with Plaso)

**Comment by beamcodeup** [comment]
Source: http://python-future.org/unicode_literals.html

I think there is a need to evaluate whether or not Python 2 or Python 3 should be used in our codebase. The link lists the pros and cons between py2 and py3. I'm more of leaning toward the latter, but would like to get your inputs on this.

**Comment by beamcodeup** [comment]
Based on the discussion off the line, Python2 is the default choice here.

**Comment by aarontp** [comment]
Yep -- With an eye towards forwards compatibility with 3 where possible.
Thanks!

**Comment by aarontp** [comment]
Closing this one out -- Thanks @beamcodeup!
