### ISSUE TITLE
[FR]: API server - provide endpoint "config download" to download original configuration

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#1514]
The current API call config.list will output the configuration as JSON by design. Provide endpoint that will output original Turbinia config file so it can be edited/re-used with Turbinia.

**Comment by jleaniz** [comment]
Not a bug. That API output by design is JSON format.  It seems you're asking for a feature that just lets you download the configuration file instead.

**Comment by hacktobeer** [comment]
Understood, rewritten and labeled as enhancement.
