### ISSUE TITLE
[Bug]: Web UI large request completion percentage incorrect

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#1556]
### What steps will reproduce the bug?

When a request has a large number of tasks and is close to completion the Web UI will incorrectly round up to 100 in the "status" column for the request.  For example if there are 331 tasks out of 333 it will show as 100.  May just need to round down instead of up.

### What is the expected behavior?

I would expect it to show 99% instead of 100%.

### What do you see instead?

Status shows 100%

**Comment by wajihyassine** [comment]
I don't believe this is a bug in the web ui check out the logic here it does already round and I'm using success+failed tasks / total tasks: https://github.com/google/turbinia/blob/942ec314c190890feb54d40cdf55d718a5a00edd/web/src/components/RequestList.vue#L193

**Comment by aarontp** [comment]
It looks like it is doing a normal math Round, but that means it will round something like 99.7 to 100, so I think we probably actually want to do a `Floor` calculation instead of `Round` and show 99 in this case and not 100. 

Here is an example output of what `turbinia-client status request <req id>` shows for a request exhibiting this behavior which is 281+51/333 == 332/333 == ~0.99699, but we see 100% in the UI.   

```
* Failed tasks: 51
* Running tasks: 0
* Successful tasks: 281
* Task Count: 333
```
