### ISSUE TITLE
Evaluate alternate config file formats

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#162]
Right now the config file written in python, which works great for the built-in client, but we're starting to want to read this from other sources (e.g. init scripts, Golang client, etc).  We should consider what would work best as a generic format.  Possibly INI?

**Comment by aarontp** [comment]
FYI: @beamcodeup @adamjnichols

**Comment by adamjnichols** [comment]
I think that this might be broken into two sections as we discussed, with separate conf instances for clients vs. servers.  Might also be interesting to be able to do so dynamically, by providing a client with a project/region combo and allow it to call to obtain the rest of the config, allowing the server to remain master.

**Comment by aarontp** [comment]
I'm going to close this one for now.   We don't have an immediate need for this, but can open it up again later if needed.
