### ISSUE TITLE
Handle overload scenarios gracefully

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#175]
PSQ has removed support for its MultiprocessWorker, and so this means that the worker tasks are currently single-threaded which means that when all of the workers are in use, new requests that come in will sit on the PubSub Queue until a worker is free and can potentially time out.  Some random options off the top of my head:

1. Preemptively spawn new workers when we are running low, or dynamically scale workers (#105).
2. Add support for multiprocessing back into PSQ
3. Create another internal queue in the task manager that keeps track of the workers and number of outstanding tasks that will only queue a task when there is room.  This is kind of lame though since I think this is something that the Task Queue should be able to handle.
4. Change our Task Queue backend (again)

We can't just block incoming requests when we are full because a request can have many tasks, so we could see failures mid-request when new tasks are created.

I'm leaning towards 1 since we can solve both problems at once, but it may be a non-trivial amount of work.

**Comment by beamcodeup** [comment]
gRPC has plans to support client-side fork by TBD in future (#14892). With that, we'll need to find out if this roadmap is in alignment with PSQ.

**Comment by aarontp** [comment]
Now that we are primarily using GKE to scale workers automatically I don't think we need to spend much time on this.  After we migrate to the new architecture we will no longer be using PSQ either, so we could potentially take advantage of some Celery features to handle this more gracefully for "local" installs if that is needed.  I'm going to close this out for now, and we can re-open this if we see a need for it for local installs in the future.
