### ISSUE TITLE
Handle separate dependencies as "extras"

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#184]
Now that we're adding new local backend types, we should try to separate our dependencies into different package sets.   One way to do that is with package "extras" as per here:
http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

Full set of dependencies by role. 

  | gcp-client | gcp-worker | gcp-server | local-client | local-worker | local-server
-- | -- | -- | -- | -- | -- | --
PSQ | x | x | x |   |   |  
Celery / redis |   |   |   |   | x | x
kombu |   |   |   | x |   | x
Plaso |   | x |   |   | x |  
GoogleCloud | x | x | x |   |   |  

Proposed simplified package groups:

  | gcp | gcp-worker | local | local-worker
-- | -- | -- | -- | --
PSQ | x | x |   |  
Celery / redis / kombu |   |   | x | x
Plaso |   | x |   | x
GoogleCloud | x | x |   |  

Notes:
* The simplified roles combines the client and the server (for cloud it was no different anyway), and for local that means installing unneeded dependencies (celery/redis on the client).
* When installing locally, this will look like `pip install .[gcp]`, and for remote Pypi packages it will be `pip install turbinia[gcp]`.
* This means that there are no common packages to all dependency groups.  I'm not 100% sure what this means for requirements.txt, but from what I understand the requirements.txt should still have a super-set of the packages.   I think this also means that when the packages are on PyPi, that just installing 'turbinia' wouldn't have any packages, and we'd have to install turbinia[gcp].  Ideally we would have something like turbinia[gcp] be the default, but I'm not sure how to do that since we don't want to install the cloud deps when we install turbinia[local].
* For "hybrid" installs (using cloud infrastructure but local workers), the `gcp` and `gcp-worker` package groups are what should be used.

Maybe there is a better way to do this?  @berggren @ericzinnikas, I'm soliciting feedback on this, so LMK if you have thoughts.

**Comment by ericzinnikas** [comment]
Seems simple enough. Internally, we're probably going to install Plaso through a packaging system (i.e. yum) instead of pip anyway, so splitting local / local-worker is handy.

**Comment by aarontp** [comment]
@berggren: Let me know if you have any thoughts on this, otherwise I think we can implement this with the four different dependency groups for now (gcp, gcp-worker, local, local-worker).

**Comment by aarontp** [comment]
After talking with @berggren out of band, here's another option for package sets:

  | default | worker | local
-- | -- | -- | --
PSQ | x |   |  
Celery / redis / kombu |   |   | x
Plaso |   | x |  
GoogleCloud | x |   |  

This way:
* a typical cloud turbinia client (and server) only needs to pip install turbinia
* All workers (local and gcp) need to install turbinia[worker]
* For local installs this means clients and servers need to install turbinia[local], and local workers need to install turbinia[local] and turbinia[worker].
* This also means that local installs will have extra unneeded cloud packages, but this is the trade-off with having a default 'pip install turbinia' working.

@ericzinnikas @berggren how does that sound?

**Comment by berggren** [comment]
SGTM

**Comment by ericzinnikas** [comment]
Yeah, that's fine. I will probably try to figure out a way to do without requiring the cloud packages, since that will make life simpler for me when deploying this internally (but that will probably just mean commenting out a few lines from `setup.py` in a fork).

**Comment by ericzinnikas** [comment]
#182 now has these changes.

**Comment by aarontp** [comment]
Thanks @ericzinnikas .

Fixed in #182.
