### ISSUE TITLE
Make sure default behavior with no config is sane

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#191]
If no config file is available turbinia gives some strange errors.  We should make sure that it's sane.

**Comment by aarontp** [comment]
Now that the config reading was moved in #427, this should be a little easier.  I think we need to:
- Change `config/__init__.py` to not attempt to read the config in `config/turbinia_config.py`.
- Add a try/except block for `TurbiniaConfigException` in `turbiniactl` with an error message around how to create a config file.

A couple clean-up things that could be done at the same time:
- Move config_turbinia_config.py to somewhere to make it more obvious that it's a template config (I don't think anything else is referencing this, but we should make sure).
- Change the `TurbiniaConfigException` to be just `TurbiniaException` as is used everywhere else.

**Comment by johngalvin** [comment]
I think this has mostly been addressed by by #447, so closing it out -- I think I hit the major points from your comment above, but I didn't exhaustively test/investigate all the turbiniactl angles in particular, so please reopen and route back to me if you spot any additional places that need better handling or more cleanup work on this. Thanks!
