### ISSUE TITLE
Selective imports of Celery/Redis

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#201]
In #182 we added support for alternate local backends (yay!), and in setup.py we have the dependencies properly segregated, but some of the modules common to both installation types still load the celery/redis modules.  We should find a way to guard these against import in the non-local case.

@ericzinnikas Any chance you want to take a look at this? :).  I haven't looked to closely, so I'm not sure what the best solution is, but we could try to check the config and selectively load them.  Or we could load them further down in the file closer to the code that uses it.  At worst we could add a try/except around them.  LMK if you might have time for this, otherwise I'll try to take a look at it soon.  Thanks!

**Comment by aarontp** [comment]
FYI, @berggren added try/except blocks in #194, but it would be nice to have a more elegant solution too.

**Comment by ericzinnikas** [comment]
Should we just use a couple if/elif blocks (`if config.TASK_MANAGER == 'PSQ'`, etc.) for this? Does the job, but I wonder if there's a nicer way.

**Comment by aarontp** [comment]
Fixed in #223.  Thanks!
