### ISSUE TITLE
Add Worker Task locks

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#221]
Now that we have more Tasks that are run on the same Evidence files, we are seeing some failures due to race conditions on the Tasks when they try to operate on the same piece of evidence.  For example, if a Task tries to attach a cloud disk while another Task on that Worker node already has that mounted, it will fail.

Rather than try to detect that and have Evidence coordination happen outside of the Task, I think we should just add some locking to the Tasks so that only one Task runs at a time on a given Worker.  Many tasks use all available resources on the Worker anyway (e.g. Plaso).  One option is to just run a single thread in the worker, but that can also have problems if there are no available Workers, then Tasks might get dropped on the ground (though as long as you have enough Workers, this is probably a good workaround until we can implement locking).  I think we can have the Tasks accept the requests, but then block if there are other Tasks running.   I implemented some very basic locking as a test, and it seems to work.  Next step is to implement this in a less hacky way.

FYI @berggren , LMK if you have any thoughts here.

**Comment by ericzinnikas** [comment]
FWIW I opted for the single-threaded strategy with the Celery workers ([here](https://github.com/google/turbinia/blob/0a7db85ea08355fd048598ebee75a18e209fb7c8/turbinia/celery.py#L101-L102)). Celery is pretty aggro about pulling tasks, so without that 1 worker would grab the first few jobs. Though in this case, if there aren't enough workers, tasks will just sit in the queue.

**Comment by aarontp** [comment]
Fixed by #245
