### ISSUE TITLE
Instance ID not being set correctly

### ISSUE THREAD

**Issue by rgayon** [google/turbinia#228]
```
$ turbiniactl -w -a -p 10 directory -l /tmp/
```
And on the turbinia server side:
```
$ turbiniactl server
<SNIP>
[INFO] Adding PSQ task GrepTask with evidence PlasoCsvFile to queue
[DEBUG] Updating Task PsortTask in Datastore
[DEBUG] Updating Task GrepTask in Datastore

[INFO] 0 Tasks still outstanding.
[ERROR] Task GrepTask from hostname.machine was not successful
[DEBUG] Updating Task GrepTask in Datastore
```

The log file is:
```
~$ cat /mnt/turbinia/output/1534209775-0af2e32809684b019cde47a1b1d27b54-GrepTask/worker-log.txt
No patterns supplied, exit task
```

**Comment by rgayon** [comment]
In turbinia/turbiniactl.py changing 
`instance=config.PUBSUB_TOPIC,` to `instance=config.INSTANCE_ID,`
seems to fix the "0 Tasks found, 1 completed. Waiting 10 seconds." from the client

**Comment by aarontp** [comment]
Yeah, it looks like when the INSTANCE_ID config var was added as part of the "local" installation type, that it didn't get changed for the cloud/hybrid types at the same time, and before that we were just using the PUBSUB_TOPIC since it was a unique string.  I'll send a PR, thanks!
