### ISSUE TITLE
Set version in only one place

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#270]
Right now the version is set in setup.py and in turbinia/__init__.py.  We should have it set in one place so we don't need to update it in both.

**Comment by Komish** [comment]
I've opted for another option (listed as option 3 [here](https://packaging.python.org/guides/single-sourcing-package-version/) in preliminary testing and a have a branch ready, but have not submitted a PR until I hear back with your preferences. 

The option details separating out the version information into a standalone module `version.py`. This allows us to restructure `__init__.py` to completely remove the version, and instead point references (only 1 spotted in in `turbiniactl.py`) to this module `from turbinia import version`.

Thoughts?

**Comment by aarontp** [comment]
@Komish That would great, thanks much!!  Could we do something similar to Option 6 in the link you reference?  If you need an example of how that can be done, it would be nice to stay consistent with one of our related projects, and this is how they are managing it: https://github.com/log2timeline/plaso/blob/master/setup.py

**Comment by Komish** [comment]
@aarontp understood, I'll align the implementations.
