### ISSUE TITLE
Programatically setting config file

### ISSUE THREAD

**Issue by tomchop** [google/turbinia#293]
I am trying to write tests for the dftimewolf turbinia module. Loading the configuration on a system that doesn't have one will fail, so I am trying to manually feed in a test config data to see if the module behaves as expected.

I tried setting the `TURBINIA_CONFIG_PATH` environment variable, but this just *adds* the path the list of possible config paths. This would work in a pristine test environment, but it will break in my dev setup where I already have a production turbinia config file set up.

What do you think of giving `TURBINIA_CONFIG_PATH` environment variable precedence over the other potential config locations?

**Comment by aarontp** [comment]
Sure, yeah, I think that should be fine.  LMK if you want to create a PR for this, otherwise I might get to it at the end of the week.
