### ISSUE TITLE
When a report is written, have a way to store Evidence info

### ISSUE THREAD

**Issue by rgayon** [google/turbinia#298]
This is mostly a note for myself:
in the pattern:
'extract these bad files and make a report', how do we preserve how we found those. Evidence.local_path may only point to a temporary local mount_point, where we woud like:
'This was in RawDisk image.dd, in DockerContainer ID blablabla'

**Comment by aarontp** [comment]
@rgayon: Is this issue still relevant? or did #309 fix this?

**Comment by aarontp** [comment]
Going to close this one since this mechanism now exists with the `Evidence.parent_evidence` property.
