### ISSUE TITLE
Make init scripts kill worker properly

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#303]
Right now the init script won't kill psqworker properly because it needs a SIGTERM instead of a SIGINT.  We should find a way to send the correct signal.

@beamcodeup Any idea on a good way to parameterize this so it works correctly for both the server and the worker?

**Comment by beamcodeup** [comment]
https://github.com/google/turbinia/blob/master/tools/turbinia%40.service

Which signal does the server need to be killed?

Change the value of KillSignal to SIGTERM and let me know if that works.

**Comment by aarontp** [comment]
@beamcodeup, Yeah, if I change it to SIGTERM, that does work for killing the worker, but that means that we have to copy this to a separate template file if a worker is running on the same machine as the server.   We could change it to SIGTERM for both, but I was just wondering if there was an easy way to have it send the correct signal depending on which service it is.  For some reason I thought we had it working that way at some point.

**Comment by aarontp** [comment]
Closing this since the psq library handles this properly when running the python3 version.
