### ISSUE TITLE
Correctly handle symlinks in directory watcher

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#31]
Right now we will process the symlink as a file, but we should follow the symlink before adding the file to be processed.

**Comment by jleaniz** [comment]
@aarontp Not sure about the context of this issue. Is it related to worker tasks?

**Comment by aarontp** [comment]
This is related to this script: https://github.com/google/turbinia/blob/master/tools/dir_watch.sh, but it's not really used anymore, so we can probably close this out.
