### ISSUE TITLE
Add system dependency check

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#312]
Now that we're adding back the bulk_extractor task (#311), we should add a mechanism to check for dependencies before Jobs are registered.  For the existing Jobs/Tasks this is pretty easy because the dependencies are all pure python, but bulk_extractor it it's own non-python binary. 

It would be easy to add a method to the Job that can be run prior to registering, but the problem is that this will run on the server which has a different set of dependencies (it doesn't need everything that's on a worker).   One option would be to set the server up with the same dependencies, but that's kind of lame for a few reasons.  Possibly a better option would be to have the Job create a new Task that gets scheduled on a worker to check the dependencies.  I think the only potential downside to that (other than complexity) is potential race conditions between when the Server and the Workers are started.  Currently the Server does not have a start-time dependency on having the Workers up (obviously there is a run-time dependency on having Workers up though).  Having the dependency check done at start-up only on the Worker wouldn't work easily because there is not currently a way for the Worker to send messages directly to the Server to disable the relevant Jobs.

One other option would be not to do the dependency check at start-up time at all, but rather when the Tasks are run on a worker, the first thing it could do is run the dependency check, and if it fails, return a special status in the TurbiniaTaskResult that when returned will cause the Server to disable any Jobs that can schedule that kind of Task.

Another factor to consider soon will be whether the dependency is Dockerized or not, so we'll have to check accordingly: https://github.com/google/turbinia/issues/444

**Comment by wajihyassine** [comment]
Feature implemented per https://github.com/google/turbinia/pull/464, closing this one out.
