### ISSUE TITLE
save_files not saved after execution failures

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#331]
When running `TurbiniaTask.execute(foo, save_files=[])`, the save_files are not saved when there are errors in the binary execution.  This is by design because generally the files in save_files list are created by the execution, so if the execution fails, the status and existence of the save_files is in an undefined state.  For example though, in the Plaso Task, the Plaso log file which is created doesn't get saved, which means that failures are difficult to debug. 

I think adding a new `log_files` parameter to `task.execute()` that would save even if the execution fails would work.  It would basically be the same thing as the existing `save_files`, but would always be saved.

**Comment by JonathanKoester** [comment]
I'm pretty new to open source and working on code I didn't write myself in general so I just wanted to make sure I understood this correctly. Are you essentially wanting log_files to do the exact same thing save_files does in execute except outside of the conditional that prevents the for loop from running? If that is the case, is there a reason for making log_files a parameter instead of just copying save_files into log_files?

**Comment by aarontp** [comment]
Hi @JonathanKoester!   That would be great, thanks!  Yeah, it's always a good idea to check with the project maintainers before starting work on a new project just to make sure that everyone is on the same page.

l'm envisioning `log_files` being similar to `save_files`, except that the files referenced in `log_files` will *always* be saved, whereas the files in `save_files` are only saved when the execution is successful.  I wouldn't want to just copy `save_files` into `log_files` because if the execution fails, then we don't want to save the `save_files` because they will be in an undefined state.  I think the `log_files` can be saved somewhere around https://github.com/google/turbinia/blob/9a31566bfdb623fd8f0f58d0ef7642231489f755/turbinia/workers/__init__.py#L281

Thanks!  Let me know if you have any other questions.

**Comment by JonathanKoester** [comment]
Okay, that makes sense. I think I understand what needs to be done now.

**Comment by aarontp** [comment]
Closing this now since #340 was merged. Thanks!
