### ISSUE TITLE
Fix linter to catch quote inconsistencies

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#351]
For some reason the linter doesn't seem to be catching some issues, or at least it doesn't seem to be triggering for quote usage inconsistencies (as in https://github.com/google/turbinia/pull/343/files).

**Comment by jleaniz** [comment]
@aarontp I believe this has been fixed at some point, i have seen pylint warnings about this.

**Comment by aarontp** [comment]
Ok, great, we can close this out then.
