### ISSUE TITLE
Add task mid-run update mechanism

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#356]
Right now we don't have much insight into the status of a given Task while it is running.  For example once a Task is scheduled we don't have any updates until the task is complete (not even what host the Task is running on).  We should add a way for the Tasks to give more updates, especially when the have been picked up by a Worker and when they actually start running.  Some of the obvious options:

1) Tasks/Workers write updates directly to Datastore/Redis.
2) Add a Cloud Function Tasks/Workers can call to update status (currently these are only RO though). 
3) Add a new PubSub message that Tasks/Workers can send that the server will pick up and then write to Datastore/Redis.

**Comment by alimez** [comment]
This issue is fixed.
