### ISSUE TITLE
region issues during installation

### ISSUE THREAD

**Issue by jgrover** [google/turbinia#367]
During installation, if I have my region set to us-east4 or us-west1, I receive the error: "region not supported."  The only region that worked for me was "europe-west1."

**Comment by aarontp** [comment]
Interesting.  At what step do you get that error?  I use us-central1 without problems, but I don't think I've tried us-east or us-west.  The only component that may have more limited availability is Cloud Functions, but I'm pretty sure that's in multiple regions as well.  Once I have more details I can take a closer look.

**Comment by jgrover** [comment]
@aarontp The error occurs when line 23 of deploy_gcf.py is executed.  It looks like it's a limitation of the gcloud command?  (Maybe?)

A colleague of mine mentioned that the command worked for him in region "us-east1" but not "us-east4".  There are definitely some limitations worth documenting in terms of which region you select.

**Comment by aarontp** [comment]
Ok, yeah, that is for the cloud functions then.  Here are the locations for where that is supported: https://cloud.google.com/functions/docs/locations.  For now Turbinia will have to exist in one of those regions when using GCP, but if that's an issue we can look at running cloud functions from a separate region.

I'll update the docs to reflect this.

**Comment by aarontp** [comment]
Fixed in https://github.com/google/turbinia/commit/2020cf9c11bc9f548efbdbc6f5c9af1b70d81395#diff-64407d3e6d5ef382426bdfbcae040c6a
