### ISSUE TITLE
Local installation requires filled-out GCP section of config

### ISSUE THREAD

**Issue by jgrover** [google/turbinia#368]
I'm attempting to get Turbinia working locally on a laptop. The laptop has internet for at least the installation part of this process.

Running into an issue with the config. I set the TASK_MANAGER to use Celery, but the installation process is still requiring me to have values for:

- TURBINIA_PROJECT
- TURBINIA_ZONE
- TURBINIA_REGION
- BUCKET_NAME

According to the instructions in the config, these values should only matter if the TASK_MANAGER is set to PSQ.

**Comment by aarontp** [comment]
Hrm, those should not be required variables, so you should be able to set them to None.  What are they set to right now?  See here for what variables are required vs. optional:
https://github.com/google/turbinia/blob/d42bad06b1758a0b89ae873e99a75c09ecdbf0aa/turbinia/config/__init__.py#L37

**Comment by jgrover** [comment]
I'm wondering if it's because I originally had the STATE_MANAGER set to an incorrect value.  Will have to test again later.

**Comment by aarontp** [comment]
Yeah, quite possible.  Right now for local installations, both the STATE_MANAGER and TASK_MANAGER need to be set to redis/celery respectively (and for GCP they should be set to datastore/psq respectively).  In theory, mixing them could work, but for now it's untested and not-recommended.  I'll make a note of this in the docs, and will update the comments in the config file too.
