### ISSUE TITLE
error running a local server

### ISSUE THREAD

**Issue by jgrover** [google/turbinia#370]
When running `turbiniactl -R server`, I get the following error:

> [INFO] Turbinia version: 20181004
> [ERROR] --run_local flag is not compatible with server/worker flags

I thought turbinia could run a server and workers locally?  My TASK_MANAGER is currently set to Celery.

**Comment by ericzinnikas** [comment]
`-C` is the flag you will want to use if you're intending to use Celery instead of GCP (include it when starting the server, workers and sending requests). We're working on updating the documentation.

`-R` will:
> Run completely locally without any server or other infrastructure. This can be used to run one-off Tasks to process data locally.

**Comment by aarontp** [comment]
Thanks for the report @jgrover and the answer @ericzinnikas :)

I think this one is solved now, so I'll close this, but feel free to re-open if you are still running into issues.
