### ISSUE TITLE
Replace deprecated oauth2client

### ISSUE THREAD

**Issue by joachimmetz** [google/turbinia#373]
Per https://pypi.org/project/oauth2client/

```
Note: oauth2client is now deprecated. No more features will be added to the
libraries and the core team is turning down support. We recommend you use google-auth and oauthlib.
```

**Comment by aarontp** [comment]
Thanks @joachimmetz .  FYI @berggren:  This dependency comes from libcloudforensics.  We should chat about what we want to do here.

**Comment by aarontp** [comment]
This was fixed upstream in the new libcloudforensics repo.
