### ISSUE TITLE
Add EWF evidence type(s)

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#377]
We should add a new evidence type for EWF along with pre/post-processors that know how to create a loop device and mount them so that other Tasks besides Plaso can also process them.

**Comment by joachimmetz** [comment]
FYI EWF can be multiple evidence types: disk, memory, optical, logical

**Comment by aarontp** [comment]
Yeah, the intention here would be to support just the E01 disk format to start.

**Comment by aarontp** [comment]
Fixed by https://github.com/google/turbinia/pull/1112
