### ISSUE TITLE
Unify paths attribures accross Evidence types

### ISSUE THREAD

**Issue by rgayon** [google/turbinia#389]
see the Compound evidence doc

**Comment by rgayon** [comment]
Plan of action:

- [ ]  Have workers stop relying on local_path
- [ ]  currently, TurbiniaTaskResult will discard Evidence with an empty (as in 'None', not existing path, or path pointing to an empty file). Is this WAI?
- [ ]  local_path is set by the output_manager when retrieving an evidence from it saved_path

**Comment by rgayon** [comment]
The workers using local_path:

- [ ] turbinia/workers/tomcat.py
- [ ] turbinia/workers/strings.py
- [ ] turbinia/workers/__init__.py
- [ ] turbinia/workers/artifact.py
- [ ] turbinia/workers/analysis/jenkins.py
- [ ] turbinia/workers/analysis/wordpress.py
- [ ] turbinia/workers/grep.py
- [ ] turbinia/workers/hadoop.py
- [ ] turbinia/workers/worker_stat.py
- [ ] turbinia/workers/sshd.py
- [ ] turbinia/workers/psort.py
- [ ] turbinia/workers/plaso.py

**Comment by aarontp** [comment]
@rgayon : Is there anything else that needs to be done here?  Maybe just update the developing new tasks doc?

**Comment by rgayon** [comment]
Probably not.
THis is also most likely very very stale
