### ISSUE TITLE
Update setup.py

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#39]
It's out of date, and has packages listed from the previous iteration.

**Comment by aarontp** [comment]
This is still broken (packages are set up correctly, but install doesn't do the right things).  @berggren Any chance you want to take a look at this when you're separating out the client configs?

**Comment by berggren** [comment]
Ack, will take care of it.

**Comment by berggren** [comment]
@aarontp could you elaborate a bit on "dependencies I believe are set up correctly, but install doesn't do the right things". What is it doing wrong?

**Comment by aaqaishtyaq** [comment]
hey @aarontp @berggren I want to work on this. can you guide me where to start

**Comment by aarontp** [comment]
Hi @aaqaishtyaq !  Sorry I missed your message here.  I think in this case @berggren actually ended up cleaning this up in #183 .  I'd be happy to point you to other issues that we could use help with though. :)  Thanks for your interest.

Fixed by #183.
