### ISSUE TITLE
Export file hashes in Plaso Task

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#403]
Plaso hashes all files automatically when processing, so we should output an evidence file with the results of that (just need to add a flag to the task and collect the file).

FYI: @tomchop

**Comment by berggren** [comment]
+1 on making this a separate task

**Comment by aarontp** [comment]
This is is now a separate Task, so closing this out. https://github.com/google/turbinia/blob/master/turbinia/workers/binary_extractor.py
