### ISSUE TITLE
Autogenerate turbiniactl command args from evidence objects

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#41]
We should autogenerate all of the commands and command args for turbiniactl based on the evidence object types and attributes so that all evidence types can be added through tubiniactl without needing to manually keep things in sync.

**Comment by aarontp** [comment]
When we do this, we probably also want to add --dump_json support so that we can easily export all the evidence objects/properties for other clients to use.

**Comment by aarontp** [comment]
Also, we should look at `click` if we are refactoring command line args.

**Comment by aarontp** [comment]
We can also use a Manager pattern similar to the Jobs manager for this.

**Comment by jleaniz** [comment]
This has been addressed in the new turbinia api cli tool. #1126
