### ISSUE TITLE
Dockerize Turbinia components and dependencies

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#429]
We're starting to gain more external binary dependencies (e.g. bulk_extractor), and we want to try to isolate those kinds of executions and at the same time make it more simple to satisfy and build the dependencies when installing  and configuring Turbinia.

**Comment by aarontp** [comment]
(FYI @berggren )

**Comment by aarontp** [comment]
This issue could probably be split into multiple docker issues, but for now I'll just keep it as one and rename it.   Here are the different dockerization things I think would be good to do.  I'm open for comments though since I don't know a lot about Docker and how things are normally done. 

1) P1: Dockerize the Turbinia client so that it's easy to deploy:  The client is the priority here since that will have the most users and they are more likely to be running on different OS platforms that aren't supported by Turbinia.

2) P1: Dockerize the binary dependencies:  This is so that we can at least run these in a container for ease of deployment (some tools are difficult to deploy, e.g. bulk_extractor) and also some level of system isolation.  This is also needed because we are starting to get more un-trusted third party code (again, bulk_extractor) as system/binary dependencies.  I've added a separate issue (https://github.com/google/turbinia/issues/440) for doing true sandboxing of these dependencies, but hopefully there is some easy way to do this along with the dockerization.

2a) A variant of 2) could be to just dockerize the entire worker process along with the dependencies.  I'm not sure which makes more sense.

3) P2: Dockerize the client/server/worker for "local" Turbinia installs (e.g. celery/redis/kombu stack):  It would also be really nice to be able to easily deploy the local version of Turbinia.  Right now it is kind of a pain because all of the dependent servers need to be set up as well.

4) P3: Dockerize for... AWS:  I'd actually really like to be able to support AWS in an easy to deploy manner as well.  This is so I can start doing some more experimental work on fully supporting AWS.

5) P3: Dockerize the server/worker for cloud:  I think this is a pretty low priority because we have the Terraform scripts that are going to be submitted soon.  It's a "nice to have" if it's trivial to do in addition to the other things.

**Comment by aarontp** [comment]
FYI @rgayon and @berggren since I've talked to you both about various components of this.

**Comment by aarontp** [comment]
FYI, https://github.com/google/turbinia/issues/444 is to track the Turbinia support for using dockerized dependencies as in option 2 above.

**Comment by rgayon** [comment]
2) could also help with some "sudoing" woes. We'd just have to expose data inside the container and do whatever needs to be as root inside of it.

**Comment by aarontp** [comment]
Lots of progress made in https://github.com/google/turbinia/pull/550.

**Comment by aarontp** [comment]
These cases should all be covered by the work done by @hacktobeer .  Closing this out.
