### ISSUE TITLE
Add support for task execution of dockerized dependencies

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#444]
This issue is to cover making sure we have a flexible way of executing binary dependencies that may be dockerized.  There is a separate issue (https://github.com/google/turbinia/issues/429) for the actual dockerization of various Turbinia components.   For example we'd like for the PlasoTask to support executing Plaso as a native binary local to the system or within a Docker container.  This should likely be done in the `TurbiniaTask.execute()` method, and ideally this should be mostly transparent to the actual Task itself.  

Couple other thoughts:
- For a first iteration we can probably get away with not having a per-Task configuration for whether it should execute in a container or not, and only have a global config entry for that. 
- Once we do have a per-task configuration, either the Task can have an attribute set on where the execution should happen, or possibly the `execute()` method could add an extra `docker` argument for that.

**Comment by wajihyassine** [comment]
Feature implemented per: https://github.com/google/turbinia/pull/488 so will close this out.
