### ISSUE TITLE
Add a README That Explains this Project

### ISSUE THREAD

**Issue by sroberts** [google/turbinia#45]
Hey @berggren (& other Googlers!),

I've heard this project referenced multiple times, and I'm super curious, but the README doesn't really give much of an idea what this project is for. Is it like a Salt/Puppet/Ansible thing? Is it an orchestration platform? I know I could read the code, but that's a big investment. A decent README that explains what this project is about would go a long way to helping folks evaluate if it's helpful.

Thanks!

**Comment by aarontp** [comment]
Good idea. :).  I have a draft of this that I've been meaning to fix up.  I'll try to do that soon.

**Comment by sroberts** [comment]
@aarontp: Thank you very much for doing this! re https://github.com/google/turbinia/pull/46
