### ISSUE TITLE
FinalizeRequestTask missing case

### ISSUE THREAD

**Issue by cteodor** [google/turbinia#453]
When a finalizerequestjob runs with local job (celery worker), FinalizeRequestTask:run() in finalize_request.py, instantiates client with TurbiniaClient() instead of TurbiniaCeleryClient().
That is, I think a client factory would be needed there to check if config.STATE_MANAGER is redis and create a TurbiniaCeleryClient instead.

**Comment by aarontp** [comment]
Good catch, yeah, you're right.  It should be a fairly quick fix.  I'll try to get to this tomorrow or possibly Friday.

FYI, I've started writing some end-to-end tests that would catch this kind of thing, but those will be a couple more weeks before I'll be able to finish them.

**Comment by aarontp** [comment]
Also, thanks for the issue reports!

**Comment by aarontp** [comment]
Fixed by #487
