### ISSUE TITLE
Unneeded call to gce_operation

### ISSUE THREAD

**Issue by sa3eed3ed** [google/turbinia#460]
https://github.com/google/turbinia/blob/a6901cbad08826e584ff2884b24686fc56851002/turbinia/lib/libcloudforensics.py#L545

a call to gce_operation here in unneeded. this should be self._data =operation directly
gce_operation will call _execute_operation and return operation directly since block is always equal False, in addition to that block can't be True because we can only pull operation objects from requests that mutate data and get requests don't, trying to pull an operation for a get request will result in an HttpError 404 

also the value returned is not always the recent value since some fields can change after setting self._data: ex. if we call get_value('status') for a vm while starting or shutting down this will not bring the updated value, might make sense to make it:

operation = self.get_operation().execute()
self._data = operation

**Comment by aarontp** [comment]
This has been fixed upstream in libcloudforensics, so I'm closing this out:
https://github.com/google/cloud-forensics-utils/blob/06d1367f0ac43d6af6248cbf56e11d1f70f4044d/libcloudforensics/gcp.py#L697
