### ISSUE TITLE
Consider reporting total run time with turbiniactl status

### ISSUE THREAD

**Issue by rgayon** [google/turbinia#466]
I imagine each task can report their own run time and the command could display the sum of all of those. This could be interesting even if that sum is different than the time it took to process everything because we're running multiple workers

**Comment by aarontp** [comment]
Have you looked at `turbiniactl status --statistics`?  I'm not sure if it has exactly what you're looking for, but it would be fairly easy to adapt if not.   You can use the normal flags for the `status` command  (e.g. `-r <request id>`, `-d <days>`, `-u <user>`, and `-t <task>`) to filter on just the jobs/tasks you're interested in.

**Comment by aarontp** [comment]
@rgayon Is this still an open issue/FR?  Let me know if `turbiniactl status --statistics` doesn't give you what you're looking for here.

**Comment by aarontp** [comment]
@rgayon :  I'm going to close this for now as I think that the `--statistics` flag can be used here, but feel free to re-open if your use-case doesn't match.
