### ISSUE TITLE
More descriptive evidence output names

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#468]
Because of the changes to disk based pre-processors in #388 the Evidence paths now point to loop devices instead of the original file/device path.  This means that that some tasks (e.g. strings) that use this path to generate the output file name no longer have the original name in them, and instead end up with names like `loop3.ascii`.  Sometimes these original filenames are descriptive or at least identify the evidence, so it would be nice if we could use the original names somehow, or come up with something that is more descriptive.

FYI @rgayon @wajihyassine

**Comment by rgayon** [comment]
SHould we use the "parent's parent's...." evidence name for creating files?
We could have a GetOriginalName() method that follows the parents list to reach the submitted evidence name

**Comment by aarontp** [comment]
@rgayon: That sounds like it would help in some cases, but even when using just a `RawDisk` Evidence type (which doesn't have any parents) we'll still see this loop device.

**Comment by rgayon** [comment]
It will have `name=args.name`, and we can go for each task make sure they use Evidence.name instead of Evidence.XXXX_path ?

**Comment by aarontp** [comment]
@rgayon : Yeah, one potential problem there too is that `Evidence.name` can be any descriptive string even though it's rarely actually used that way (so it could have characters we wouldn't want in a path).   Maybe we add a `GetOriginalName()` as you suggested, but also add an attribute for `original_path` that always gets set in `Evidence.__init__()`?
