### ISSUE TITLE
 BinaryExtractorTask Task failed with exception: [[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by wajihyassine** [google/turbinia#471]
Running into the BinaryExtractorTask failing when I'm running the PSQWorker. Note that I have not specified any files to extract so may just need to do some error handling/checking to skip the task if nothing was specified. 
```
[ERROR] BinaryExtractorTask Task failed with exception: [[Errno 2] No such file or directory: '/var/tmp/1575655625-2bab288734d940629f369de30b7c89a6-BinaryExtractorTask/extracted_binaries/hashes.json']
[ERROR] Traceback (most recent call last):
  File "/turbinia/turbinia/workers/__init__.py", line 637, in run_wrapper
    self.result = self.run(evidence, self.result)
  File "/turbinia/turbinia/workers/binary_extractor.py", line 94, in run
    binary_cnt, hash_cnt = self.check_extraction()
  File "/turbinia/turbinia/workers/binary_extractor.py", line 52, in check_extraction
    with open(self.json_path) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/1575655625-2bab288734d940629f369de30b7c89a6-BinaryExtractorTask/extracted_binaries/hashes.json'

[ERROR] BinaryExtractorTask Task failed with exception: [[Errno 2] No such file or directory: '/var/tmp/1575655625-2bab288734d940629f369de30b7c89a6-BinaryExtractorTask/extracted_binaries/hashes.json']
[INFO] Traceback (most recent call last):
  File "/turbinia/turbinia/workers/__init__.py", line 637, in run_wrapper
    self.result = self.run(evidence, self.result)
  File "/turbinia/turbinia/workers/binary_extractor.py", line 94, in run
    binary_cnt, hash_cnt = self.check_extraction()
  File "/turbinia/turbinia/workers/binary_extractor.py", line 52, in check_extraction
    with open(self.json_path) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/1575655625-2bab288734d940629f369de30b7c89a6-BinaryExtractorTask/extracted_binaries/hashes.json'
```

**Comment by aarontp** [comment]
@wajihyassine: I don't think you should have to specify anything in particular, IIRC it should just automatically extract all binaries.   There may some other bug, but this probably at least needs some checks (at least to make sure the file exists before opening it).

FYI @meeehow

**Comment by meeehow** [comment]
I think that this is because you don't have the most recent version of Plaso installed on your machine. Image_export.py runs fine, but it does not generate hashes.json file, which is a new feature. 

@aarontp - how do you want to proceed here? We could throw more descriptive error in case the file does not exist, but in general the job should fail when there is no hashes.json file.

**Comment by aarontp** [comment]
@meeehow: Yeah, I think a more descriptive error message, including something like "make sure you have at least version X deployed" would be good here.

**Comment by aarontp** [comment]
@meeehow If it's ok, I'm going to assign this to you, but feel free to unassign it if you don't think you'll get to it.  Thanks!
