### ISSUE TITLE
Migrate from cloud function calls to http trigger

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#481]
Cloud function direct calls seem to have a drastically different quota that we sometimes run into when setting the poll parameter <= 5.  We should swap over to HTTP triggers since they are also synchronous.

**Comment by aarontp** [comment]
Typical error:
```
Quota exceeded for quota group 'TestCall' and limit 'Test function requests per 100 seconds' of service 'cloudfunctions.googleapis.com'
```

FYI @berggren

**Comment by aarontp** [comment]
I believe this is the interface we are using today: https://cloud.google.com/functions/docs/calling/direct

And I think this is likely what we want to be using instead: https://cloud.google.com/functions/docs/calling/http

Note that we also need to update the cloud functions API version.

**Comment by alimez** [comment]
It looks like that it's already using http trigger to make cloud function calls. https://github.com/google/turbinia/blob/2afeea47cd6fcad41e92528c347e7d97db6d8655/tools/gcf_init/deploy_gcf.py#L25

**Comment by aarontp** [comment]
@alimez  I think the problem with the interface we're using is the way we're invoking the function, specifically by using this `call()` method, which this page indicates that it's just for testing:
https://cloud.google.com/functions/docs/reference/rest/v1beta2/projects.locations.functions/call

Here is where that is being invoked:
https://github.com/google/turbinia/blob/53435c6d68cf85ec497437b0faa0dd32beb2c21d/turbinia/lib/google_cloud.py#L300

Here are the rate limits and quotas for the various cloud function related parts, including the call limit we're seeing in the error message above:
https://cloud.google.com/functions/quotas#rate_limits

Looking closer, I don't see any other direct way to call it through the built service API (even though the API is just http/REST).  I didn't see any other obvious python client libraries for this either, but I did a cursory search (google-cloud-functions is something written by a third-party and doesn't look very maintained).  We might need to use the 'requests' library or something similar to build a  request outside of any other library.

**Comment by alimez** [comment]
There are multiple ways of doing this. A doc was created and shared with the aarontp.

**Comment by aarontp** [comment]
Given that we are migrating away from GCF to an API server I'm going to close this one out.
