### ISSUE TITLE
Implement additional configuration options for docker client init

### ISSUE THREAD

**Issue by wajihyassine** [google/turbinia#490]
In order for Turbinia to use Docker, the host system has to have the Docker daemon installed and the client is initialized with the system environment variables. We can allow further customization in the configuration file for Docker client init to allow users to specify a docker host to connect to, API version, default timeout settings, tls, and user agent to use. I think regardless, for Turbinia to work with Docker, the Docker daemon has to be on the same host as Turbinia, but this may allow for a little more customization.

**Comment by aarontp** [comment]
Closing this out as we've now gone down the path of putting the entire worker in the Docker container instead of executing individual Tasks in docker.
