### ISSUE TITLE
Remove parse_dependencies from setup.py

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#492]
It looks like the pip API changed in recent versions and `parse_requirements()` is not supported as it is an internal only method.

Here are a couple related issues:
https://github.com/pypa/pip/issues/5599
https://github.com/pypa/pip/issues/7645

Part of the stacktrace:
```
    Traceback (most recent call last):
      File "setup.py", line 29, in <module>
        from pip._internal.download import PipSession
    ModuleNotFoundError: No module named 'pip._internal.download'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "setup.py", line 32, in <module>
        from pip.download import PipSession
    ModuleNotFoundError: No module named 'pip.download'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Here's the pip documentation linked from one of the bugs:
https://pip.pypa.io/en/stable/user_guide/#using-pip-from-your-program

**Comment by aarontp** [comment]
Looks like Timesketch has a similar issue, but Plaso/dftimewolf use different mechanisms.
https://github.com/google/timesketch/issues/1094

**Comment by loganbek** [comment]
hitting similar.

**Comment by aarontp** [comment]
Temporary fix is in #493, and I'll patch it into the release branch and cut a release later today.

**Comment by aarontp** [comment]
Release branch and new release pushed.  Will keep this open to track a longer term fix to remove using pip from setuptools at all.

**Comment by aarontp** [comment]
This was fixed in https://github.com/google/turbinia/pull/524
