### ISSUE TITLE
Add datastore retries

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#495]
Getting this intermittently when trying to start tasks:
```
[ERROR] Failed to update task PlasoTask in datastore: 409 too much contention on these datastore entities. please try again. entity groups: [(app=s~bar, TurbiniaTask, "foo")]
```

We should add some retries for this.

**Comment by jleaniz** [comment]
@aarontp Do we want to keep or close this out since it rellates to gcp datastore?

**Comment by aarontp** [comment]
Yeah, we can close this out, thanks.  I'm pretty sure we've already added this for Redis, but we can always re-open if we do see symptoms of this again.
