### ISSUE TITLE
Add server count variable to Terraform config

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#512]
Right now we can adjust the number of workers to run in the Terraform config, but we don't have a way to adjust the server count.  In full cloud installations this is fine, but if we want to use the Terraform config for Hybrid or dev installs it would be nice to be able to set the server count to zero so that it won't deploy the server.  The workaround of course is just to delete the server after it is deployed.

Here's where the worker count is set:
https://github.com/forseti-security/forseti-security/blob/f1ecc3d5691569168f676ffc733a9b6a7a507249/contrib/incident-response/infrastructure/modules/turbinia/variables.tf#L60

FYI: @berggren

**Comment by alimez** [comment]
PR was submitted and merged to address this.
