### ISSUE TITLE
Update l2tscaffolder to use new reporting

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#518]
The Turbinia Task templates in https://github.com/log2timeline/l2tscaffolder need to be updated to use the new Task report templating.

**Comment by aarontp** [comment]
I'm not sure if anyone is really using l2tscaffolder anymore, but it does look like it's been updated (for Timesketch) within the last year.  

@hacktobeer I know you have plans on working on the developer experience for Tasks, do you think it's worth incorporating l2tscaffolder into that, or should we just close this out?

**Comment by hacktobeer** [comment]
Was not aware that this existed. I am not that much of a fan, seems overkill for us and another thing (outside of the Turbinia repo) to maintain.

**Comment by aarontp** [comment]
Sounds good, let's just close this out then for now.
