### ISSUE TITLE
Update turbiniarc generated by terraform

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#520]
Right now Terraform generates a config compatible with the latest release branch, but in order to deploy more recent versions we'll need to add some of the new config variables.  A workaround for right now is to copy them from the config template (https://github.com/google/turbinia/blob/master/turbinia/config/turbinia_config_tmpl.py) into the generated config.

**Comment by alimez** [comment]
https://github.com/forseti-security/forseti-security/pull/3747

**Comment by alimez** [comment]
This is fixed by forseti-security/forseti-security#3747
