### ISSUE TITLE
Rewrite cloud functions in python

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#528]
Right now the cloud functions are written in javascript since when we wrote them originally GCF didn't support python, but now that it does, we should probably rewrite them.

**Comment by alimez** [comment]
Adding the other cloud functions issue #481 to this one. This can also address the other issue.

**Comment by aarontp** [comment]
Closing this out as we are moving away from cloud functions to an API server in the new architecture and don't want to spend any more time on the existing GCF implementation.
