### ISSUE TITLE
Move away from oauth2client

### ISSUE THREAD

**Issue by tomchop** [google/turbinia#534]
The oauth2client lib in https://github.com/google/turbinia/blob/master/turbinia/lib/google_cloud.py#L32 has been deprecated, and moved to `google-auth`

**Comment by joachimmetz** [comment]
Related https://github.com/google/turbinia/issues/373

**Comment by aarontp** [comment]
Yeah, I closed out the other one since I didn't realize that it needed to be fixed here too even after libcloudforensics was moved out.  This should be fixed now in #535
