### ISSUE TITLE
Add support to process forensic artifacts with plaso

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#536]
Turbinia can process disks, it would be very helpful if Turbinia can process non-disk artefacts with plaso and push those to timesketch. 

Having the possibility to process artefacts instead of full disks means we can investigate faster and only fetch the artefacts we need with whatever acquisition tools is used. Not all (most?) investigations need the whole disk processed.

**Comment by aarontp** [comment]
This can be done with local/hybrid installations with the `Directory` evidence type, but this doesn't work for cloud though.   The way we've talked about doing that in the past is to  convert `Directory` into a `CompressedDirectory` on the client side, and then auto-upload it to GCS for processing.  I'll repurpose this bug to handle auto-upload of certain evidence types, and I filed https://github.com/google/turbinia/issues/538 for the client side conversion.

LMK if you have other ideas about how this could be handled differently.

**Comment by hacktobeer** [comment]
I am not too familiar with the Turbinia architecture but my workflow would ideally be that I have a set of artifacts pulled from a host (eg, browser history files and registry file) and I would zip those up and use the Turbinia CLI tool to kick off a Plaso job and providing the zip file for the CLI tool to upload to Turbinia/GCS.

**Comment by wajihyassine** [comment]
Issue fixed here: https://github.com/google/turbinia/pull/569
