### ISSUE TITLE
Terraform: Don't require cloudshell for execution

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#565]
Now that we're depending more on `deploy.sh` within terraform (as opposed to just raw terraform), it would be nice to have a way that doesn't require cloudshell.  We can probably work around it by setting appropriate environment variables, but we should at least start by documenting what those are.

**Comment by hacktobeer** [comment]
export DEVSHELL_PROJECT_ID=`gcloud config list --format 'value(core.project)'`

^ that sets the correct project id wherever it is run. You can also set it manually of course. With this set you can run the Turbinia terraform stuff outside of cloudshell.

**Comment by aarontp** [comment]
Fixed in https://github.com/forseti-security/osdfir-infrastructure/pull/10
