### ISSUE TITLE
Add label/name to stackdriver logs

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#588]
This will make it easier to find and query the right logs.

https://googleapis.dev/python/logging/latest/usage.html#writing-log-entries
https://googleapis.dev/python/logging/latest/usage.html#cloud-logging-handler

**Comment by alimez** [comment]
The following queries should work depending on which setup you're using. 

For non-dockerized GCE/Hybrid setup:
```
logName="projects/{PROJECT_NAME}/logs/python"
```
For dockerized setup:
```
logName="projects/{PROJECT_NAME}/logs/cos_containers"
```

**Comment by alimez** [comment]
Fixed
