### ISSUE TITLE
Create thin client

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#627]
The current turbiniactl is a thick client, it contains all worker and server dependencies as it's also used to run the server and workers. As workers contain many tasks with all kinds of forensic dependencies this makes the use case to have a simple client to only schedule jobs complicated.

Let's see if it's feasible to create a thin client that people can install (with minimal dependencies) to send jobs to a a turbinia setup.

**Comment by aarontp** [comment]
Closing in favor of dupe #1126
