### ISSUE TITLE
Workers output directory fills up docker containers

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#645]
Right now the default output directory used by the terraform install is /var/lib/turbinia, and this is in the container and not shared with the host OS.  The containers are very small by default (`/` is 5.7G), and they fill up very quickly.

I'm not sure what the best solution is, but I think binding/sharing this as a directory on the host would probably help since we can more easily resize that.

@hacktobeer LMK if you have a better idea than binding the output dir to the host, thanks!

**Comment by hacktobeer** [comment]
* Cleaning up that folder if files are not needed anymore? I don't know what is currently written to it.
* Mounting a dedicated external 'data' disk to that path

**Comment by aarontp** [comment]
Basically all output is written there initially so we'll need some buffer space (especially for things like strings, but even a single plaso file will fill that up).   In addition to this we need to find a good way to clean things up though (https://github.com/google/turbinia/issues/348). 

For posterity, here is a PR with a (broken) fix: https://github.com/forseti-security/osdfir-infrastructure/pull/16

**Comment by aarontp** [comment]
We added a second disk to be created at deployment time, so I think we can close this out.
