### ISSUE TITLE
turbiniactl status --workers not showing results

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#647]
Even though datastore is updated with the correct worker information after the task has been completed, the worker view doesn't show the workers:

```
$ turbiniactl  status --workers
[INFO] Turbinia version: 20190819
[INFO] Disabling non-allowlisted jobs configured to be disabled in the config file: volatilityjob
# Turbinia report for Worker activity within 7 days
* 0 Worker(s) found.
* 14 Task(s) unassigned or scheduled and pending Worker assignment.
```

FYI @wajihyassine

**Comment by wajihyassine** [comment]
I debugged the `turbinia status --workers` command and manually added in 'running' to the status for testing. It doesn't look like the data is being pulled properly from datastore as that value did not exist to test how the worker status function is parsing the values so issue may be connected to retrieving data from datastore.

**Comment by wajihyassine** [comment]
Retested with some queued tasks and the `turbiniactl status --workers` command did display correctly. I also manually changed one of the queue tasks to "running" and then reran `turbiniactl status --workers` which picked up and displayed both `queued` and `running` tasks. This further confirms a potential issue with the data being pulled from datastore.

**Comment by wajihyassine** [comment]
hmm now after spinning up a new server/worker and kicking off a new test job to process then running `turbiniactl status --workers` after a minute, I get results back in console for Running and Queued workers.

**Comment by aarontp** [comment]
After doing some debugging with @wajihyassine , it looks like https://github.com/google/turbinia/issues/653 is the root of the problem, and it's not an issue with the workers status code so closing this one out.
