### ISSUE TITLE
Plaso worker installation silently overwrites pyyaml used by hindsight

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#688]
When installing the worker we need plaso and hindsight installed. Plaso uses an older version of pyyaml (on ubuntu 18.04) that is required by hindsight. As plaso is installed with apt-get it will silently overwrite pyyaml with and older version. Installing hindsight *after* plaso is not possible as the new pip version will not uninstall distutil installed packages (like the pyyaml installed by plaso).

We need to fix this by eg upgrading to a newer version of ubuntu for the base image or install plaso in a different way (eg through pip instead of apt-get).

**Comment by aarontp** [comment]
Closing this out now that we are using 20.04 as our base image.
