### ISSUE TITLE
Generate version data from tags and commits

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#694]
Today we have a hard-coded value in `turbinia/__init__.py`, but it would be nice to generate the version number from the current TAG for releases and from the git commit id when there is no TAG (ie. when running from master or a different branch).

**Comment by aarontp** [comment]
FYI @hacktobeer

**Comment by hacktobeer** [comment]
```
$ turbiniactl -V
20190819.4.dev118+g9ca7def.d20210128
```

Draft PR here #696.

**Comment by hacktobeer** [comment]
Local example on how it looks if you create a new tag.
```
$ git tag 20210128
$ python3 setup.py install
$ turbiniactl -V
20210128.dev0+g2f8f37f.d20210128
```
