### ISSUE TITLE
Evaluate whether we really need keyrings.alt included

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#711]
See comments in https://github.com/google/turbinia/pull/709/files for details.

**Comment by hacktobeer** [comment]
I agree, it's something upstream. I added it as I want our builds to work (the error happens on ubuntu 18.04, it did not happen on my mac).
https://pantheon.corp.google.com/cloud-build/builds;region=global/f349ff6c-3675-4609-a2d7-19c00b1b2bbe?project=osdfir-registry
Line 1617.

I'll try to rebuild without this somewhere next week and remove the alt keyring when it succeeds/
