### ISSUE TITLE
Fix up evidence descriptive names

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#718]
Evidence objects have a `__str__` method that gives us a name based on some properties of the object, including the `source_path`.  When using compound evidence types with parent evidence objects, the source path can be somewhat meaningless (e.g. `/dev/loop3`).  We should clean these up so that we're using useful names, possibly by using something in the parent evidence objects.  We could potentially override this per evidence type when needed as well.

**Comment by dfjxs** [comment]
@aarontp I think this was fixed in #1073

**Comment by aarontp** [comment]
Cool, right, thanks!
