### ISSUE TITLE
Remove old bitlocker Evidence types

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#761]
Now that we have native support for bitlocker encryption, we can remove the old Evidence type.  As part of this we'll want to update the Plaso Task to use the new credentials flags/location.

**Comment by aarontp** [comment]
FYI @dfjxs

**Comment by dfjxs** [comment]
The Plaso task won't be using DiskPartition evidence though.
Just making sure we're all on the same page, but the plan is still to have Plaso manage it's own decryption, it will just take the credentials from the source evidence object?

**Comment by aarontp** [comment]
Yes, the Plaso task will continue to use the Disk Evidence types and not the Partition type.  For that we just need to change where it's getting the credentials from (since that's in the base Evidence class, we should be OK).  We don't have any other Tasks that use the Bitlocker Evidence type though, so AFAIK we should be fine to remove that completely.
