### ISSUE TITLE
Disable file logging when not running worker/server

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#788]
Right now when turbiniactl runs, even just as a client, it will enable file logging as per the path set in the configuration file.  This is really only needed for the server and the worker, and if the user running the client wants to set a separate log file with command line flags they can.  We should turn off  default file logging for the client because otherwise if it's using the exact same config file as the worker/server it will try to log to the same path.  The workaround is to have a separate config, but that's not ideal.

**Comment by hacktobeer** [comment]
I agree this is an issue although I think the solution is in separating worker/server and client code. Mixing in more duplicate flags (eg in logging flag in config and in cli) will be confusing. Let's just fix this in the refactor of thin-client code.

**Comment by aarontp** [comment]
I think separating client/server code is different from this (though it could  be fixed when doing that separation).  Even once the client is separated, we'll still use the same module to read the config file (because it still needs to know the parameters to talk to the server) and the same module to set up the logging handlers.  We already have all the flags we need to specify the log paths too, so all that really needs to be done is just not enable the file log handler by default when we're not running as a server/worker.

**Comment by hacktobeer** [comment]
I hope the thin-client will not have to be configured with a configuration
file like the worker/server tbh.....a thin-client would be thin and not
need cloud libraries etc.
