### ISSUE TITLE
turbiniactl does not show help when only config is specified

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#789]
When you run `turbiniactl` with no arguments it will show the help as expected, but when you run it with `-c` to specify a config file to run with, it gives a non-intuitive error.  We should fix this to show the help message in that case.

```
2021-03-11 07:12:42 [INFO] Turbinia version: unknown
2021-03-11 07:12:43 [WARNING] Command None not implemented.
2021-03-11 07:12:43 [INFO] Done.
```

**Comment by sosa-e** [comment]
Hello! I am new to open source, and I would like to work on this

**Comment by aarontp** [comment]
@sosa-e Sorry, I didn't see this older comment until now.  I'm actually going to close this out because most of the features of this tool have been moved to turbinia-client and users will not be using this interactively (it's only used for start/stop of components).   There are some other issues with the `good first issue` label if you're still interested in contributing.  Thanks!
