### ISSUE TITLE
Add Redis timeout

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#818]
Currently when starting the server/worker when configured to use Redis/Celery, it will indefinitely hang (or at least hang for a very long time, ie. several minutes) and it's not clear what it's hanging on.  We should add some kind of timeout and useful error message for that condition.

**Comment by nagavenkateshgavini** [comment]
@aarontp I would like to work on this task, please assign me.

**Comment by aarontp** [comment]
@nagavenkateshgavini sure, sounds good, thanks!
