### ISSUE TITLE
Configure devcontainer to start redis on start

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#819]
As far as I can tell from the vs code devcontainer config, Redis is configured to start at VM creation time, but not at VM start time by default:
https://github.com/google/turbinia/blob/43457f7f706d18d95cf3bdbdb9467bda3efcf5b3/.devcontainer/devcontainer.json#L9

We should add the systemd commands to enable starting by default (or the right commands in the devcontainer config to start it at start time as well).

**Comment by aarontp** [comment]
FYI @hacktobeer

**Comment by bhushan-borole** [comment]
Hey @aarontp 
I would like to work on this issue.
Could you please share some light on this topic

**Comment by hacktobeer** [comment]
He, sure thing. So we have a devcontainer.json file that can be used to develop locally using vscode. As our stack uses redis it starts a redis server as shown in the first issue comment. This is nice but we also need the redis container to start on sebsequent starts of the devcontainer and not only at creation. 

See here for information on using a devcontainer with vscode:  https://code.visualstudio.com/docs/remote/containers
See here for the development flow as we use this with Turbinia: https://turbinia.readthedocs.io/en/latest/developer/develop-vscode.html

**Comment by bhushan-borole** [comment]
Hey @hacktobeer 
I just looked into the docs: https://code.visualstudio.com/docs/remote/devcontainerjson-reference
And I am assuming I have to use `postStartCommand`.
Am I right?

**Comment by hacktobeer** [comment]
That looks about right, make sure you test it in a local setup (both that redis is started the first time at creation and the second and subsequent times at startup) as described in https://turbinia.readthedocs.io/en/latest/developer/develop-vscode.html

A PR including the startup info from vscode would be awesome.

**Comment by bhushan-borole** [comment]
@hacktobeer 
My local machine is Apple Silicon, will I be able to run this ?

**Comment by hacktobeer** [comment]
Both docker (to run the devcontainer) and vscode are support on M1s.

**Comment by bhushan-borole** [comment]
That's superb, I'll look right into it.
Thanks @hacktobeer

**Comment by bhushan-borole** [comment]
Hey @hacktobeer 
I think the `postStartCommand` does the job.
I started the redis server using that .
Attaching the terminal output.
<img width="1178" alt="Terminal Output" src="https://user-images.githubusercontent.com/37565807/126348241-cfe513a9-348b-4dfa-9fd3-4290d9cd2361.png">


Let me know if I am doing anything wrong.

**Comment by bhushan-borole** [comment]
Attaching the terminal output, after building the container.
<img width="1178" alt="Terminal Output" src="https://user-images.githubusercontent.com/37565807/126348801-b6b33948-a88e-4623-a317-99727ee7c112.png">

Am I going in the right direction?

**Comment by hacktobeer** [comment]
It seems it's run twice now, so moving it to only the startcommand makes sense. Feel free to create a PR and I'll comment on that.
