### ISSUE TITLE
Add Turbinia monitoring management to SRE script

### ISSUE THREAD

**Issue by alimez** [google/turbinia#837]
The current SRE script does not allow for changing prometheus and grafana change. We need to add this to the SRE script in order to make changes (updating SMTP config, disks, general config, etc) to the monitoring instances

**Comment by hacktobeer** [comment]
Although I understand the ask, is this something that will happen often?
The SRE mgmt script has functionality for often used use cases. I am
wondering if updating the Prometheus and Grafana settings (eg SMTP) is
worth adding to a management script if it only happens once a year or less.
Probably doing this manually makes more sense as they are one offs. Wdyt?

**Comment by alimez** [comment]
Some pieces of it are one time thing that can be done manually. However, adding a feature to be able to add new environment variables to monitoring containers can be pretty handy as we expand our use of prometheus/grafana.

**Comment by hacktobeer** [comment]
Good one, let's see if I can make that more generic. The env vars for
containers are not exposed through the API and are embedded in a big string
blob. I'll have a look at it.
Agree that it would be good functionality to have!

**Comment by aarontp** [comment]
Closing this out since we use helm / osdfir-infrastructure for deployment management now.
