### ISSUE TITLE
Docker (local) build fail on Ubuntu 20.04

### ISSUE THREAD

**Issue by Vetpeet** [google/turbinia#838]
When following these instructions: [ https://turbinia.readthedocs.io/en/latest/user/turbinia-local-stack.html ](url) on Ubuntu 20.04 to spin up a local docker instance of Tubinia the following issue occur.

`WARNING: The PWD variable is not set. Defaulting to a blank string.
Starting turbinia-worker ... done
Starting local_redis_1   ... done
Starting turbinia-server ... done
Attaching to turbinia-worker, local_redis_1, turbinia-server
redis_1            | 1:C 09 Jul 2021 00:01:24.584 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1            | 1:C 09 Jul 2021 00:01:24.584 # Redis version=6.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1            | 1:C 09 Jul 2021 00:01:24.584 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1            | 1:M 09 Jul 2021 00:01:24.584 * monotonic clock: POSIX clock_gettime
redis_1            | 1:M 09 Jul 2021 00:01:24.585 * Running mode=standalone, port=6379.
redis_1            | 1:M 09 Jul 2021 00:01:24.585 # Server initialized
redis_1            | 1:M 09 Jul 2021 00:01:24.585 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1            | 1:M 09 Jul 2021 00:01:24.586 * Loading RDB produced by version 6.2.4
redis_1            | 1:M 09 Jul 2021 00:01:24.586 * RDB age 82808 seconds
redis_1            | 1:M 09 Jul 2021 00:01:24.586 * RDB memory usage when created 0.77 Mb
redis_1            | 1:M 09 Jul 2021 00:01:24.586 * DB loaded from disk: 0.000 seconds
redis_1            | 1:M 09 Jul 2021 00:01:24.586 * Ready to accept connections
turbinia-worker    | grep: /etc/turbinia/turbinia.conf: No such file or directory
`

It would appear that the config file is not read/found.

**Comment by aarontp** [comment]
Thanks for the report.

@hacktobeer Could you potentially take a look at this?  I wouldn't think it had anything to do with using 20.04 as the host, but I don't think I've tried that specifically.

**Comment by aarontp** [comment]
FWIW, this same issue has also been reported by others on Slack.

**Comment by hacktobeer** [comment]
Seem the server and worker can not find the turbinia.conf.

* Make sure that (following the instructions) the turbinia.conf is available in the created 'conf' folder (See Step 2).
* Make sure you execute Step 3 (docker-compose ,,,, ) from the parent folder where you created the 'conf' folder as docker-compose tries to mount $PWD/conf into the container.

This will fix your issue. Should you run into permission issues for the 'evidence' folder -> chmod 777 evidence

Just tested this on a clean 20.04 install following the instructions and comes up without issues.

Should you have more issues, please include the output of a 'ls -al' from the folder you execute Step 3 (docker-compose...) from.

**Comment by Vetpeet** [comment]
Thank you for the feedback @AaronP, I can confirm that the conf folder is created and does contain the turbinia.conf file.
Also I am running the docker-compose command from within the Parent dir /etc/turbinia.
docker-compose is breaking before creating the 'evidence' folder. 

![Screenshot from 2021-07-12 08-26-41](https://user-images.githubusercontent.com/17916334/125215398-bdded500-e2fe-11eb-9213-caed4d54474f.png)

**Comment by hacktobeer** [comment]
Thanks for the extra info. Couple of things I notice:
* the turbinia.conf file is present in the parent folder, is it also present in the ./conf folder?
  * ls -al ./conf 
* can you also create and make a 'evidence' folder accessible before starting docker-compose?
   * mkdir evidence 
   * chmod 777 evidence

Feel free to provide the docker-compose output here so we can have a look.

**Comment by hacktobeer** [comment]
As mentioned on Slack:

* docker-compose should *not* be run as root (eg sudo)
* this sets $PWD to blank
* $PWD is used to mount the Turbinia configuration into the container.

Please
* run docker-compose as non-root (see  https://docs.docker.com/engine/install/linux-postinstall/)
* or change the path in docker-compose.yml to point to the local full path of the turbinia.conf file

**Comment by Vetpeet** [comment]
Thank you @hacktobeer, this did resolve the issue. I had to remove the turbinia dir and clone fresh copy of repo.

**Comment by Vetpeet** [comment]
Thank you @hacktobeer, this did resolve the issue. I had to remove the turbinia dir and clone fresh copy of repo.
