### ISSUE TITLE
e2e tests: Gather worker/server logs

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#857]
We gather several logs from the client when running the e2e tests, but it would be nice to have the full worker and server logs as well given that the infrastructure is taken down immediately after a test.  Another nice to have would be turning on debug logging when Turbinia is deployed for e2e tests.  Maybe we can gather the logs with the new `update-gcp-infra.sh` script.

**Comment by aarontp** [comment]
The default enabling of debug level logs on the server/worker can now be done by passing in `--debug-logs` to `deploy.sh`: https://github.com/forseti-security/osdfir-infrastructure/pull/54

**Comment by hacktobeer** [comment]
---debug-logs has been added to all e2e tests.

Will fetch worker/server logs in post test task.

**Comment by hacktobeer** [comment]
Getting the actual log files from the workers/server is a bit more complicated as we run a docker image (worker/server) in a GCE containeros instance and these get created dynamically each time a test runs. A smarter way would be to dump both server and worker logs from stackdriver as comntaineros stdout/stderr is logged there anyway.
