### ISSUE TITLE
Race condition in losetup mount check running multiple workers on same host

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#906]
When running multiple workers on the same host the below check can generate an Error while it's not. When 1 worker has released the loop device a second worker immediately picks it up the check below will show an existing loop device (now used by the second worker).

https://github.com/google/turbinia/blob/master/turbinia/processors/mount_local.py#L371

**Comment by hacktobeer** [comment]
Extra check: are loop devices actually deleted when a task fails? (PostprocessDeleteLosetup)

**Comment by aarontp** [comment]
@hacktobeer / @wajihyassine : I think this is this fixed now with the recent changes to locking, is that right?

**Comment by wajihyassine** [comment]
Yep moving `_postprocess` under lock mechanism should have fixed it and can close this out
