### ISSUE TITLE
turbiniactl command to retrieve result data

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#91]
ie. get .plaso files from GCS or wherever the new Evidence objects are written to.

**Comment by aarontp** [comment]
Note:  The paths to the files can be seen with 'turbiniactl -a status', but we still want a convenience mechanism to download the file itself.

**Comment by aarontp** [comment]
I'm thinking something like:
turbiniactl dumpresults  -r <request id> -o <my dump directory>
or
turbiniactl dumpresult -t <task id> -o <my dump directory>

And it will gather all of the file results associated with that request or task and dump it to the given directory.

Note this is also a dependency for timesketch integration.

**Comment by alimez** [comment]
fixed #667
