### ISSUE TITLE
Results should be stored grouped per request

### ISSUE THREAD

**Issue by hacktobeer** [google/turbinia#914]
Currently Turbinia stores results in a flat folder structure with a folder per task. It would be a lot more convenient if output was stored in a structure with a folder per request.
Example: https://github.com/google/turbinia/commit/b9bf9dcaac2cbadb217278c77a5b90d4d286760b

**Comment by alimez** [comment]
Since we are also adding group_id to turbinia, perhaps it's better to make the group_id the parent folder -> request_ids ->  task_ids  respectively

**Comment by hacktobeer** [comment]
As long as it's clear to the user what the group ID is when creating a
request (eg the client always returns a group ID).
It should be easy for a user to navigate the output structure on disk.
