### ISSUE TITLE
Create a default recipe for processing Linux artifacts with Plaso

### ISSUE THREAD

**Issue by wajihyassine** [google/turbinia#957]
Create a default recipe, similar to [Windows Triage Recipe](https://github.com/google/turbinia/blob/master/turbinia/config/recipes/triage-windows.yaml) that will process a subset of  important artifacts for Linux hosts (e.g. /var/log, crontabs, user home directories) which would speed up processing time

**Comment by tomchop** [comment]
Adding filesystem timeline too, I'd say.
