### ISSUE TITLE
Create a default recipe for processing macos artifacts with Plaso

### ISSUE THREAD

**Issue by wajihyassine** [google/turbinia#958]
Create a default recipe, similar to [Windows Triage Recipe](https://github.com/google/turbinia/blob/master/turbinia/config/recipes/triage-windows.yaml) that will process a subset of important artifacts for MacOS hosts (e.g. /var/log, persistence locations, user home directories) which would speed up processing time

**Comment by tomchop** [comment]
+ filesystem timeline, I would say
