### ISSUE TITLE
maintenance: dfImageTools GetBodyfileEntries will issue deprecation warning in version 20220127

### ISSUE THREAD

**Issue by joachimmetz** [google/turbinia#983]
This is mostly a head-up

In https://github.com/log2timeline/dfimagetools/releases/tag/20220127 the GetBodyfileEntries was marked as deprecated (https://github.com/log2timeline/dfimagetools/blob/20220127/dfimagetools/file_entry_lister.py#L118). The functionality has been moved into a separate BodyfileGenerator class (https://github.com/log2timeline/dfimagetools/blob/20220127/dfimagetools/bodyfile.py#L10)

Use of GetBodyfileEntries will issue a deprecation warning as version 20220127. No timeline has been set yet to remove this method.

It is recommended to update to Turbinia's usage of dfImageTools, at the earliest convenient time.

**Comment by aarontp** [comment]
@jleaniz Do you think you could take a look at this when you get a chance?

**Comment by aarontp** [comment]
Actually it looks like there is already a fix in #984 .  @joachimmetz Could you confirm whether there is anything else outside of that PR that we need to handle on our end?

**Comment by joachimmetz** [comment]
@aarontp FYI, I'll set up a gift ppa staging first, nearly done with that and I'll send a PR for turbinia CI tests to use that

then I'l get back to this PR. The issue just generates a deprecating warning for now, and I'll get this merged before removing the deprecated function
