### ISSUE TITLE
Small refactor: Add evidence to task during init

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#99]
Right now the evidence is paired with a task when the run method is called as part of the task scheduling. Since we have both in the TurbiniaJob.create_tasks function, we should add it to the task there, and keep it as a property of the object.  This will be more important when we have more elaborate create_tasks() methods.

**Comment by fpiedrah** [comment]
Hi! I would like to work in this task, but before I'll need some help understanding some of the details. 

1. All jobs are sub-classed from `interface.TurbiniaJob`, all jobs must implement the `create_tasks` method.
2. The idea is that `interface.TurbiniaJob` itself should save the `evidence` as a class property when  `create_tasks` is called? 
3. Implementing this inside `interface.TurbiniaJob.create_tasks`  method will mean that classes that inherit from `interface.TurbiniaJob` would override the aforementioned `evidence` with their own `create_tasks` behavior. 
4. One solution could be a decorator, but each time that a  `create_tasks` would be implemented it would need to use this decorator. Am I over complicating this or am I in the correct path to a solution?

**Comment by fpiedrah** [comment]
@aarontp Hi! I would like to work on this task! But I've got a couple of questions:

1) The idea is to add `evidence` as a parameter on the `__init__` method?

2) then all subclasses of `interface.TurbiniaJob` will need to be passed this evidence parameter, should it be made to be default as None in oder to avoid breaking all instances that are not currently using this way of passing the `evidence`

Or do you have any other suggestion on how to implement this? Thanks!

**Comment by aarontp** [comment]
Hi @fpiedrah!

I started looking through the code a bit to see what all needs to be done here, and I think that things have changed enough since this issue was initially filed that it might not makes sense to go through and refactor all of this.  It would be a nice minor clean-up, but it would require changing the TaskManager, all of the Jobs, and the TurbiniaTask and TurbiniaTaskResult objects, and I'm not sure if it's actually worth the effort.

We do have plenty of other good first issues though, so I'd be quite happy to point you in the direction of some of them.  Off the top of my head, either #307 or #306 would both be pretty good items to start on.  Let me know if either of those look interesting to you, and I can give you more details on those.

Thanks!  Let me know what you think.

**Comment by aarontp** [comment]
Looks like you were able to pick up one of the other issues, so I'm going to close this one for now.  Thanks!
