### ISSUE TITLE
Container timelines

### ISSUE THREAD

**Issue by aarontp** [google/turbinia#998]
We run many of the Jobs/Tasks within containers, but don't actually make a FS timeline.  We should add either the PlasoJob and/or the new FilesystemTimelineJob for this evidence type.  This *should* just be a one line change to the job to accept DockerContainer to the `evidence_input`, but we should test it to make sure it works and that the output is clear for what container this is running on (and if not we might want to include some extra metadata in the FS status/output to distinguish it).

**Comment by rjcolonna** [comment]
#1055 - add PlasoJob to read file system of a docker container

**Comment by aarontp** [comment]
Thanks @rjcolonna , I think we can close this one out now then.  I think it's OK to just have Plaso and not the FS timeline task as well since that would require a bunch of extra work AFAIK.
